import { IgxQueryBuilderComponent } from "../../../igniteui-angular/query-builder";
import { IgxGridComponent } from "../../../igniteui-angular/grids/grid";
import { IgxHierarchicalGridComponent } from "../../../igniteui-angular/grids/hierarchical-grid";
import {
  IgxPivotDataSelectorComponent,
  IgxPivotGridComponent,
} from "../../../igniteui-angular/grids/pivot-grid";
import { IgxTreeGridComponent } from "../../../igniteui-angular/grids/tree-grid";
import { IgxActionStripComponent } from "../../../igniteui-angular/action-strip/src/action-strip/action-strip.component";
import { IgxActionStripToken } from "../../../igniteui-angular/core/src/grid-column-actions/token";
import { IgxPaginatorComponent } from "../../../igniteui-angular/paginator/src/paginator/paginator.component";
import { IgxPaginatorToken } from "../../../igniteui-angular/paginator/src/paginator/token";
import { IgxColumnGroupComponent } from "../../../igniteui-angular/grids/core/src/columns/column-group.component";
import { IgxColumnComponent } from "../../../igniteui-angular/grids/core/src/columns/column.component";
import { IgxColumnLayoutComponent } from "../../../igniteui-angular/grids/core/src/columns/column-layout.component";
import { IgxQueryBuilderHeaderComponent } from "../../../igniteui-angular/query-builder/src/query-builder/query-builder-header.component";
import { IgxGridEditingActionsComponent } from "../../../igniteui-angular/grids/core/src/grid-actions/grid-editing-actions.component";
import { IgxActionStripActionsToken } from "../../../igniteui-angular/core/src/grid-column-actions/token";
import { IgxGridPinningActionsComponent } from "../../../igniteui-angular/grids/core/src/grid-actions/grid-pinning-actions.component";
import { IgxGridToolbarTitleComponent } from "../../../igniteui-angular/grids/core/src/toolbar/common";
import { IgxGridToolbarActionsComponent } from "../../../igniteui-angular/grids/core/src/toolbar/common";
import { IgxGridToolbarAdvancedFilteringComponent } from "../../../igniteui-angular/grids/core/src/toolbar/grid-toolbar-advanced-filtering.component";
import { IgxGridToolbarComponent } from "../../../igniteui-angular/grids/core/src/toolbar/grid-toolbar.component";
import { IgxToolbarToken } from "../../../igniteui-angular/grids/core/src/toolbar/token";
import { IgxGridToolbarExporterComponent } from "../../../igniteui-angular/grids/core/src/toolbar/grid-toolbar-exporter.component";
import { IgxGridToolbarHidingComponent } from "../../../igniteui-angular/grids/core/src/toolbar/grid-toolbar-hiding.component";
import { IgxGridToolbarPinningComponent } from "../../../igniteui-angular/grids/core/src/toolbar/grid-toolbar-pinning.component";
import { IgxRowIslandComponent } from "../../../igniteui-angular/grids/hierarchical-grid/src/row-island.component";
import { IgxGridStateComponent } from "../lib/state.component";

export const registerComponents = [
  IgxGridComponent,
  IgxHierarchicalGridComponent,
  IgxTreeGridComponent,
  IgxPivotGridComponent,
  IgxPivotDataSelectorComponent,
  IgxQueryBuilderComponent,
];

//// WARNING: Code below this line is auto-generated and any modifications will be overwritten
export var registerConfig = [
  {
    component: IgxActionStripComponent,
    selector: "igc-action-strip",
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxRowIslandComponent,
    ],
    contentQueries: [
      {
        property: "actionButtons",
        childType: IgxActionStripActionsToken,
        isQueryList: true,
      },
    ],
    additionalProperties: [{ name: "cdr", writable: true }],
    methods: ["show", "hide"],
    boolProps: ["hidden"],
    provideAs: IgxActionStripToken,
  },
  {
    component: IgxColumnComponent,
    selector: "igc-column",
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxPivotGridComponent,
      IgxRowIslandComponent,
      IgxColumnGroupComponent,
      IgxColumnLayoutComponent,
    ],
    contentQueries: [],
    additionalProperties: [
      { name: "grid", writable: true },
      { name: "selected", writable: true },
      { name: "index" },
      { name: "visibleIndex" },
      { name: "columnGroup" },
      { name: "columnLayout" },
      { name: "columnLayoutChild" },
      { name: "childColumns" },
      { name: "level" },
      { name: "filteringExpressionsTree" },
      { name: "parent", writable: true },
      { name: "topLevelParent" },
    ],
    methods: ["pin", "unpin", "move", "autosize"],
    templateProps: [
      "summaryTemplate",
      "bodyTemplate",
      "headerTemplate",
      "inlineEditorTemplate",
      "errorTemplate",
      "filterCellTemplate",
    ],
    numericProps: ["rowEnd", "colEnd", "rowStart", "colStart"],
    boolProps: [
      "merge",
      "sortable",
      "selectable",
      "groupable",
      "editable",
      "filterable",
      "resizable",
      "autosizeHeader",
      "hasSummary",
      "hidden",
      "disableHiding",
      "disablePinning",
      "filteringIgnoreCase",
      "sortingIgnoreCase",
      "searchable",
      "pinned",
      "visibleWhenCollapsed",
    ],
  },
  {
    component: IgxColumnGroupComponent,
    selector: "igc-column-group",
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxColumnGroupComponent,
      IgxRowIslandComponent,
    ],
    contentQueries: [
      {
        property: "children",
        childType: IgxColumnComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "selected", writable: true },
      { name: "childColumns" },
      { name: "columnGroup" },
      { name: "columnLayout" },
      { name: "grid", writable: true },
      { name: "index" },
      { name: "visibleIndex" },
      { name: "columnLayoutChild" },
      { name: "level" },
      { name: "filteringExpressionsTree" },
      { name: "parent", writable: true },
      { name: "topLevelParent" },
    ],
    methods: ["pin", "unpin", "move", "autosize"],
    templateProps: [
      "collapsibleIndicatorTemplate",
      "summaryTemplate",
      "headerTemplate",
      "errorTemplate",
      "filterCellTemplate",
    ],
    numericProps: ["rowEnd", "colEnd", "rowStart", "colStart"],
    boolProps: [
      "collapsible",
      "expanded",
      "searchable",
      "hidden",
      "merge",
      "sortable",
      "groupable",
      "editable",
      "filterable",
      "resizable",
      "autosizeHeader",
      "hasSummary",
      "disableHiding",
      "disablePinning",
      "filteringIgnoreCase",
      "sortingIgnoreCase",
      "pinned",
      "visibleWhenCollapsed",
    ],
    provideAs: IgxColumnComponent,
  },
  {
    component: IgxColumnLayoutComponent,
    selector: "igc-column-layout",
    parents: [IgxGridComponent],
    contentQueries: [
      {
        property: "children",
        childType: IgxColumnComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "columnLayout" },
      { name: "visibleIndex" },
      { name: "selected", writable: true },
      { name: "childColumns" },
      { name: "columnGroup" },
      { name: "grid", writable: true },
      { name: "index" },
      { name: "columnLayoutChild" },
      { name: "level" },
      { name: "filteringExpressionsTree" },
      { name: "parent", writable: true },
      { name: "topLevelParent" },
    ],
    methods: ["pin", "unpin", "move", "autosize"],
    templateProps: [
      "collapsibleIndicatorTemplate",
      "summaryTemplate",
      "headerTemplate",
      "errorTemplate",
      "filterCellTemplate",
    ],
    numericProps: ["rowEnd", "colEnd", "rowStart", "colStart"],
    boolProps: [
      "hidden",
      "collapsible",
      "expanded",
      "searchable",
      "merge",
      "sortable",
      "groupable",
      "editable",
      "filterable",
      "resizable",
      "autosizeHeader",
      "hasSummary",
      "disableHiding",
      "disablePinning",
      "filteringIgnoreCase",
      "sortingIgnoreCase",
      "pinned",
      "visibleWhenCollapsed",
    ],
    provideAs: IgxColumnComponent,
  },
  {
    component: IgxGridComponent,
    selector: "igc-grid",
    parents: [],
    contentQueries: [
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      {
        property: "actionStripComponents",
        childType: IgxActionStripToken,
        isQueryList: true,
      },
      { property: "toolbar", childType: IgxToolbarToken, isQueryList: true },
      {
        property: "paginationComponents",
        childType: IgxPaginatorToken,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "groupsRecords" },
      { name: "selectedCells" },
      { name: "validation" },
      { name: "gridAPI" },
      { name: "cdr" },
      { name: "navigation", writable: true },
      { name: "shouldGenerate", writable: true },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "hiddenColumnsCount" },
      { name: "pinnedColumnsCount" },
      { name: "transactions" },
      { name: "lastSearchInfo" },
      { name: "filteredData" },
      { name: "filteredSortedData" },
      { name: "virtualizationState" },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "columns" },
      { name: "pinnedColumns" },
      { name: "pinnedStartColumns" },
      { name: "pinnedEndColumns" },
      { name: "pinnedRows" },
      { name: "unpinnedColumns" },
      { name: "visibleColumns" },
      { name: "dataView" },
    ],
    methods: [
      "groupBy",
      "clearGrouping",
      "isExpandedGroup",
      "toggleGroup",
      "selectRowsInGroup",
      "deselectRowsInGroup",
      "fullyExpandGroup",
      "toggleAllGroupRows",
      "getSelectedData",
      "getRowByIndex",
      "getRowByKey",
      "getCellByColumn",
      "getCellByKey",
      "pinRow",
      "unpinRow",
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandAll",
      "collapseAll",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "moveColumn",
      "markForCheck",
      "addRow",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "reflow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedStartWidth",
      "getPinnedEndWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "clearCellSelection",
      "selectRange",
      "getSelectedRanges",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
      "beginAddRowByIndex",
    ],
    templateProps: [
      "dropAreaTemplate",
      "detailTemplate",
      "groupByRowSelectorTemplate",
      "groupRowTemplate",
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "rowExpandedIndicatorTemplate",
      "rowCollapsedIndicatorTemplate",
      "headerExpandedIndicatorTemplate",
      "headerCollapsedIndicatorTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "totalItemCount",
      "snackbarDisplayTime",
      "summaryRowHeight",
      "rowHeight",
      "totalRecords",
    ],
    boolProps: [
      "groupsExpanded",
      "hideGroupedColumns",
      "showGroupArea",
      "autoGenerate",
      "moving",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "batchEditing",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxGridEditingActionsComponent,
    selector: "igc-grid-editing-actions",
    parents: [IgxActionStripComponent],
    contentQueries: [],
    additionalProperties: [{ name: "hasChildren" }],
    methods: ["startEdit"],
    boolProps: ["addRow", "editRow", "deleteRow", "addChild", "asMenuItems"],
    provideAs: IgxActionStripActionsToken,
  },
  {
    component: IgxGridPinningActionsComponent,
    selector: "igc-grid-pinning-actions",
    parents: [IgxActionStripComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: ["pin", "unpin", "scrollToRow"],
    boolProps: ["asMenuItems"],
    provideAs: IgxActionStripActionsToken,
  },
  {
    component: IgxGridStateComponent,
    selector: "igc-grid-state",
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxPivotGridComponent,
    ],
    contentQueries: [],
    additionalProperties: [{ name: "grid", writable: true }],
    methods: [
      "applyState",
      "applyStateFromString",
      "getState",
      "getStateAsString",
    ],
  },
  {
    component: IgxGridToolbarActionsComponent,
    selector: "igc-grid-toolbar-actions",
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: [],
  },
  {
    component: IgxGridToolbarAdvancedFilteringComponent,
    selector: "igc-grid-toolbar-advanced-filtering",
    parents: [IgxGridToolbarComponent, IgxGridToolbarActionsComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: [],
  },
  {
    component: IgxGridToolbarComponent,
    selector: "igc-grid-toolbar",
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxPivotGridComponent,
    ],
    contentQueries: [
      { property: "hasActions", childType: IgxGridToolbarActionsComponent },
    ],
    additionalProperties: [{ name: "nativeElement" }],
    methods: [],
    boolProps: ["showProgress"],
    provideAs: IgxToolbarToken,
  },
  {
    component: IgxGridToolbarExporterComponent,
    selector: "igc-grid-toolbar-exporter",
    parents: [IgxGridToolbarComponent, IgxGridToolbarActionsComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: ["export"],
    boolProps: ["exportCSV", "exportExcel", "exportPDF"],
  },
  {
    component: IgxGridToolbarHidingComponent,
    selector: "igc-grid-toolbar-hiding",
    parents: [IgxGridToolbarComponent, IgxGridToolbarActionsComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: ["checkAll", "uncheckAll"],
    numericProps: ["indentetion"],
    boolProps: ["hideFilter"],
  },
  {
    component: IgxGridToolbarPinningComponent,
    selector: "igc-grid-toolbar-pinning",
    parents: [IgxGridToolbarComponent, IgxGridToolbarActionsComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: ["checkAll", "uncheckAll"],
    numericProps: ["indentetion"],
    boolProps: ["hideFilter"],
  },
  {
    component: IgxGridToolbarTitleComponent,
    selector: "igc-grid-toolbar-title",
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: [],
  },
  {
    component: IgxHierarchicalGridComponent,
    selector: "igc-hierarchical-grid",
    parents: [],
    contentQueries: [
      {
        property: "childLayoutList",
        childType: IgxRowIslandComponent,
        isQueryList: true,
      },
      {
        property: "allLayoutList",
        childType: IgxRowIslandComponent,
        isQueryList: true,
        descendants: true,
      },
      {
        property: "paginatorList",
        childType: IgxPaginatorToken,
        isQueryList: true,
        descendants: true,
      },
      {
        property: "actionStripComponents",
        childType: IgxActionStripToken,
        isQueryList: true,
      },
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      { property: "toolbar", childType: IgxToolbarToken, isQueryList: true },
      {
        property: "paginationComponents",
        childType: IgxPaginatorToken,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "foreignKey" },
      { name: "selectedCells" },
      { name: "gridAPI", writable: true },
      { name: "navigation", writable: true },
      { name: "validation" },
      { name: "cdr" },
      { name: "shouldGenerate", writable: true },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "hiddenColumnsCount" },
      { name: "pinnedColumnsCount" },
      { name: "transactions" },
      { name: "lastSearchInfo" },
      { name: "filteredData" },
      { name: "filteredSortedData" },
      { name: "virtualizationState" },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "columns" },
      { name: "pinnedColumns" },
      { name: "pinnedStartColumns" },
      { name: "pinnedEndColumns" },
      { name: "pinnedRows" },
      { name: "unpinnedColumns" },
      { name: "visibleColumns" },
      { name: "dataView" },
    ],
    methods: [
      "getRowByIndex",
      "getRowByKey",
      "getCellByColumn",
      "getCellByKey",
      "pinRow",
      "unpinRow",
      "getDefaultExpandState",
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandAll",
      "collapseAll",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "moveColumn",
      "markForCheck",
      "addRow",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "reflow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedStartWidth",
      "getPinnedEndWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "clearCellSelection",
      "selectRange",
      "getSelectedRanges",
      "getSelectedData",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
      "beginAddRowByIndex",
    ],
    templateProps: [
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "rowExpandedIndicatorTemplate",
      "rowCollapsedIndicatorTemplate",
      "headerExpandedIndicatorTemplate",
      "headerCollapsedIndicatorTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "totalItemCount",
      "snackbarDisplayTime",
      "summaryRowHeight",
      "rowHeight",
      "totalRecords",
    ],
    boolProps: [
      "expandChildren",
      "showExpandAll",
      "autoGenerate",
      "moving",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxPaginatorComponent,
    selector: "igc-paginator",
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxPivotGridComponent,
    ],
    contentQueries: [],
    additionalProperties: [
      { name: "totalPages", writable: true },
      { name: "isLastPage" },
      { name: "isFirstPage" },
      { name: "nativeElement" },
    ],
    methods: ["nextPage", "previousPage", "paginate"],
    numericProps: ["page", "perPage", "totalRecords"],
    provideAs: IgxPaginatorToken,
  },
  {
    component: IgxPivotDataSelectorComponent,
    selector: "igc-pivot-data-selector",
    parents: [],
    contentQueries: [],
    additionalProperties: [{ name: "animationSettings", writable: true }],
    methods: [],
    boolProps: [
      "columnsExpanded",
      "rowsExpanded",
      "filtersExpanded",
      "valuesExpanded",
    ],
  },
  {
    component: IgxPivotGridComponent,
    selector: "igc-pivot-grid",
    parents: [],
    contentQueries: [
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      { property: "toolbar", childType: IgxToolbarToken, isQueryList: true },
      {
        property: "paginationComponents",
        childType: IgxPaginatorToken,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "gridAPI" },
      { name: "navigation", writable: true },
      { name: "dimensionsSortingExpressions" },
      { name: "allDimensions" },
      { name: "validation" },
      { name: "cdr" },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "lastSearchInfo" },
      { name: "filteredData" },
      { name: "filteredSortedData" },
      { name: "virtualizationState" },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "columns" },
      { name: "pinnedStartColumns" },
      { name: "pinnedEndColumns" },
      { name: "visibleColumns" },
      { name: "dataView" },
    ],
    methods: [
      "notifyDimensionChange",
      "toggleColumn",
      "getColumnGroupExpandState",
      "toggleRowGroup",
      "autoSizeRowDimension",
      "insertDimensionAt",
      "moveDimension",
      "removeDimension",
      "toggleDimension",
      "insertValueAt",
      "moveValue",
      "removeValue",
      "toggleValue",
      "sortDimension",
      "filterDimension",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "markForCheck",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "clearFilter",
      "clearSort",
      "reflow",
      "getPinnedEndWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "clearCellSelection",
      "selectRange",
      "getSelectedRanges",
      "getSelectedData",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "navigateTo",
    ],
    templateProps: [
      "valueChipTemplate",
      "rowDimensionHeaderTemplate",
      "emptyPivotGridTemplate",
      "emptyGridTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "rowExpandedIndicatorTemplate",
      "rowCollapsedIndicatorTemplate",
      "headerExpandedIndicatorTemplate",
      "headerCollapsedIndicatorTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
    ],
    numericProps: ["rowHeight"],
    boolProps: [
      "autoGenerateConfig",
      "superCompactMode",
      "defaultExpandState",
      "isLoading",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxQueryBuilderComponent,
    selector: "igc-query-builder",
    parents: [],
    contentQueries: [
      {
        property: "queryBuilderHeaderCollection",
        childType: IgxQueryBuilderHeaderComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [],
    methods: ["canCommit", "commit", "discard"],
    templateProps: ["searchValueTemplate"],
    boolProps: [
      "showEntityChangeDialog",
      "disableEntityChange",
      "disableReturnFieldsChange",
    ],
  },
  {
    component: IgxQueryBuilderHeaderComponent,
    selector: "igc-query-builder-header",
    parents: [IgxQueryBuilderComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: [],
    boolProps: ["showLegend"],
  },
  {
    component: IgxRowIslandComponent,
    selector: "igc-row-island",
    parents: [IgxHierarchicalGridComponent, IgxRowIslandComponent],
    contentQueries: [
      {
        property: "children",
        childType: IgxRowIslandComponent,
        isQueryList: true,
      },
      {
        property: "childLayoutList",
        childType: IgxRowIslandComponent,
        isQueryList: true,
      },
      {
        property: "childColumns",
        childType: IgxColumnComponent,
        isQueryList: true,
      },
      {
        property: "actionStripComponents",
        childType: IgxActionStripToken,
        isQueryList: true,
      },
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
    ],
    additionalProperties: [
      { name: "rowIslandAPI", writable: true },
      { name: "gridAPI", writable: true },
      { name: "navigation", writable: true },
      { name: "validation" },
      { name: "cdr" },
      { name: "shouldGenerate", writable: true },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "transactions" },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "columns" },
      { name: "pinnedRows" },
    ],
    methods: [
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandAll",
      "collapseAll",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "moveColumn",
      "markForCheck",
      "addRow",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "pinRow",
      "unpinRow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedStartWidth",
      "getPinnedEndWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "clearCellSelection",
      "selectRange",
      "getSelectedRanges",
      "getSelectedData",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
      "beginAddRowByIndex",
    ],
    templateProps: [
      "toolbarTemplate",
      "paginatorTemplate",
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "rowExpandedIndicatorTemplate",
      "rowCollapsedIndicatorTemplate",
      "headerExpandedIndicatorTemplate",
      "headerCollapsedIndicatorTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "snackbarDisplayTime",
      "summaryRowHeight",
      "rowHeight",
      "totalRecords",
    ],
    boolProps: [
      "expandChildren",
      "showExpandAll",
      "autoGenerate",
      "moving",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxTreeGridComponent,
    selector: "igc-tree-grid",
    parents: [],
    contentQueries: [
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      {
        property: "actionStripComponents",
        childType: IgxActionStripToken,
        isQueryList: true,
      },
      { property: "toolbar", childType: IgxToolbarToken, isQueryList: true },
      {
        property: "paginationComponents",
        childType: IgxPaginatorToken,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "rootRecords", writable: true },
      { name: "records", writable: true },
      { name: "processedRootRecords", writable: true },
      { name: "processedRecords", writable: true },
      { name: "selectedCells" },
      { name: "validation" },
      { name: "gridAPI" },
      { name: "cdr" },
      { name: "navigation", writable: true },
      { name: "shouldGenerate", writable: true },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "hiddenColumnsCount" },
      { name: "pinnedColumnsCount" },
      { name: "lastSearchInfo" },
      { name: "filteredData" },
      { name: "filteredSortedData" },
      { name: "virtualizationState" },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "columns" },
      { name: "pinnedColumns" },
      { name: "pinnedStartColumns" },
      { name: "pinnedEndColumns" },
      { name: "pinnedRows" },
      { name: "unpinnedColumns" },
      { name: "visibleColumns" },
      { name: "dataView" },
    ],
    methods: [
      "getDefaultExpandState",
      "expandAll",
      "collapseAll",
      "addRow",
      "beginAddRowByIndex",
      "getSelectedData",
      "getRowByIndex",
      "getRowByKey",
      "getCellByColumn",
      "getCellByKey",
      "pinRow",
      "unpinRow",
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "moveColumn",
      "markForCheck",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "reflow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedStartWidth",
      "getPinnedEndWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "clearCellSelection",
      "selectRange",
      "getSelectedRanges",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
    ],
    templateProps: [
      "rowLoadingIndicatorTemplate",
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "rowExpandedIndicatorTemplate",
      "rowCollapsedIndicatorTemplate",
      "headerExpandedIndicatorTemplate",
      "headerCollapsedIndicatorTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "expansionDepth",
      "snackbarDisplayTime",
      "summaryRowHeight",
      "rowHeight",
      "totalRecords",
    ],
    boolProps: [
      "cascadeOnDelete",
      "autoGenerate",
      "moving",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "batchEditing",
      "selectRowOnClick",
    ],
  },
];
