import {
  IgxHierarchicalGridComponent,
  IgxPivotDataSelectorComponent,
  IgxPivotGridComponent,
  IgxRowIslandComponent,
  IgxTreeGridComponent,
} from "../../../igniteui-angular/src/public_api";
import { IgxGridComponent } from "../../../igniteui-angular/src/lib/grids/grid/grid.component";
import { IgxGridToolbarAdvancedFilteringComponent } from "../../../igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component";
import { IgxGridToolbarExporterComponent } from "../../../igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component";
import { IgxGridToolbarHidingComponent } from "../../../igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component";
import { IgxGridToolbarPinningComponent } from "../../../igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component";
import { IgxGridToolbarComponent } from "../../../igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component";
import { IgxPaginatorComponent } from "../../../igniteui-angular/src/lib/paginator/paginator.component";
import { IgxColumnComponent } from "../../../igniteui-angular/src/lib/grids/columns/column.component";
import { IgxColumnGroupComponent } from "../../../igniteui-angular/src/lib/grids/columns/column-group.component";
import { IgxColumnLayoutComponent } from "../../../igniteui-angular/src/lib/grids/columns/column-layout.component";
import { IgxToolbarToken } from "../../../igniteui-angular/src/lib/grids/toolbar/token";
import { IgxActionStripComponent } from "../../../igniteui-angular/src/lib/action-strip/action-strip.component";
import { IgxGridEditingActionsComponent } from "../../../igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component";
import { IgxGridActionsBaseDirective } from "../../../igniteui-angular/src/lib/action-strip/grid-actions/grid-actions-base.directive";
import { IgxGridPinningActionsComponent } from "../../../igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component";
import { IgxGridToolbarTitleComponent } from "../../../igniteui-angular/src/lib/grids/toolbar/common";
import { IgxGridToolbarActionsComponent } from "../../../igniteui-angular/src/lib/grids/toolbar/common";

export const registerComponents = [
  IgxGridComponent,
  IgxHierarchicalGridComponent,
  IgxTreeGridComponent,
  IgxPivotGridComponent,
  IgxPivotDataSelectorComponent,
];

//// WARNING: Code below this line is auto-generated and any modifications will be overwritten
export var registerConfig = [
  {
    component: IgxPaginatorComponent,
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxPivotGridComponent,
    ],
    contentQueries: [],
    additionalProperties: [
      { name: "totalPages", writable: true },
      { name: "classCosy" },
      { name: "classCompact" },
      { name: "classComfortable" },
      { name: "isLastPage" },
      { name: "isFirstPage" },
      { name: "isFirstPageDisabled" },
      { name: "isLastPageDisabled" },
      { name: "nativeElement" },
    ],
    methods: ["nextPage", "previousPage", "paginate", "ngDoCheck"],
    numericProps: ["page", "perPage", "totalRecords"],
  },
  {
    component: IgxActionStripComponent,
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxRowIslandComponent,
    ],
    contentQueries: [
      {
        property: "actionButtons",
        childType: IgxGridActionsBaseDirective,
        isQueryList: true,
      },
    ],
    additionalProperties: [{ name: "cdr", writable: true }],
    methods: ["show", "hide", "ngDoCheck"],
    boolProps: ["hidden"],
  },
  {
    component: IgxGridEditingActionsComponent,
    parents: [IgxActionStripComponent],
    contentQueries: [],
    additionalProperties: [
      { name: "hasChildren" },
      { name: "buttons", writable: true },
      { name: "strip", writable: true },
    ],
    methods: ["startEdit", "deleteRowHandler", "addRowHandler"],
    boolProps: ["addRow", "editRow", "deleteRow", "addChild", "asMenuItems"],
    provideAs: IgxGridActionsBaseDirective,
  },
  {
    component: IgxGridPinningActionsComponent,
    parents: [IgxActionStripComponent],
    contentQueries: [],
    additionalProperties: [
      { name: "buttons", writable: true },
      { name: "strip", writable: true },
    ],
    methods: ["pin", "unpin", "scrollToRow"],
    boolProps: ["asMenuItems"],
    provideAs: IgxGridActionsBaseDirective,
  },
  {
    component: IgxColumnComponent,
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxPivotGridComponent,
      IgxRowIslandComponent,
      IgxColumnGroupComponent,
      IgxColumnLayoutComponent,
    ],
    contentQueries: [],
    additionalProperties: [
      { name: "selected", writable: true },
      { name: "autoSize", writable: true },
      { name: "calcPixelWidth", writable: true },
      { name: "index" },
      { name: "defaultMinWidth" },
      { name: "cells" },
      { name: "visibleIndex" },
      { name: "columnGroup" },
      { name: "columnLayout" },
      { name: "columnLayoutChild" },
      { name: "allChildren" },
      { name: "level" },
      { name: "isLastPinned" },
      { name: "isFirstPinned" },
      { name: "rightPinnedOffset" },
      { name: "gridRowSpan" },
      { name: "gridColumnSpan" },
      { name: "defaultWidth", writable: true },
      { name: "widthSetByUser", writable: true },
      { name: "filteringExpressionsTree" },
      { name: "parent", writable: true },
      { name: "grid", writable: true },
      { name: "cdr", writable: true },
      { name: "topLevelParent" },
      { name: "headerCell" },
      { name: "filterCell" },
      { name: "headerGroup" },
    ],
    methods: [
      "getInitialChildColumnSizes",
      "getFilledChildColumnSizes",
      "getResizableColUnderEnd",
      "pin",
      "unpin",
      "move",
      "autosize",
    ],
    templateProps: [
      "summaryTemplate",
      "bodyTemplate",
      "headerTemplate",
      "inlineEditorTemplate",
      "errorTemplate",
      "filterCellTemplate",
    ],
    numericProps: ["rowEnd", "colEnd", "rowStart", "colStart"],
    boolProps: [
      "sortable",
      "selectable",
      "groupable",
      "editable",
      "filterable",
      "resizable",
      "autosizeHeader",
      "hasSummary",
      "hidden",
      "disableHiding",
      "disablePinning",
      "movable",
      "filteringIgnoreCase",
      "sortingIgnoreCase",
      "searchable",
      "pinned",
      "visibleWhenCollapsed",
    ],
  },
  {
    component: IgxColumnGroupComponent,
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxColumnGroupComponent,
      IgxRowIslandComponent,
    ],
    contentQueries: [
      {
        property: "children",
        childType: IgxColumnComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "cells" },
      { name: "selected", writable: true },
      { name: "allChildren" },
      { name: "columnGroup" },
      { name: "columnLayout" },
      { name: "autoSize", writable: true },
      { name: "calcPixelWidth", writable: true },
      { name: "index" },
      { name: "defaultMinWidth" },
      { name: "visibleIndex" },
      { name: "columnLayoutChild" },
      { name: "level" },
      { name: "isLastPinned" },
      { name: "isFirstPinned" },
      { name: "rightPinnedOffset" },
      { name: "gridRowSpan" },
      { name: "gridColumnSpan" },
      { name: "defaultWidth", writable: true },
      { name: "widthSetByUser", writable: true },
      { name: "filteringExpressionsTree" },
      { name: "parent", writable: true },
      { name: "grid", writable: true },
      { name: "cdr", writable: true },
      { name: "topLevelParent" },
      { name: "headerCell" },
      { name: "filterCell" },
      { name: "headerGroup" },
    ],
    methods: [
      "getInitialChildColumnSizes",
      "getFilledChildColumnSizes",
      "getResizableColUnderEnd",
      "pin",
      "unpin",
      "move",
      "autosize",
    ],
    templateProps: [
      "collapsibleIndicatorTemplate",
      "summaryTemplate",
      "headerTemplate",
      "errorTemplate",
      "filterCellTemplate",
    ],
    numericProps: ["rowEnd", "colEnd", "rowStart", "colStart"],
    boolProps: [
      "collapsible",
      "expanded",
      "searchable",
      "hidden",
      "sortable",
      "groupable",
      "editable",
      "filterable",
      "resizable",
      "autosizeHeader",
      "hasSummary",
      "disableHiding",
      "disablePinning",
      "movable",
      "filteringIgnoreCase",
      "sortingIgnoreCase",
      "pinned",
      "visibleWhenCollapsed",
    ],
    provideAs: IgxColumnComponent,
  },
  {
    component: IgxGridToolbarTitleComponent,
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: [],
  },
  {
    component: IgxGridToolbarActionsComponent,
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [],
    methods: [],
  },
  {
    component: IgxGridToolbarComponent,
    parents: [
      IgxGridComponent,
      IgxTreeGridComponent,
      IgxHierarchicalGridComponent,
      IgxPivotGridComponent,
    ],
    contentQueries: [
      { property: "hasActions", childType: IgxGridToolbarActionsComponent },
    ],
    additionalProperties: [{ name: "nativeElement" }],
    methods: ["ngDoCheck"],
    boolProps: ["showProgress"],
    provideAs: IgxToolbarToken,
  },
  {
    component: IgxGridComponent,
    parents: [],
    contentQueries: [
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      { property: "actionStrip", childType: IgxActionStripComponent },
      {
        property: "toolbar",
        childType: IgxGridToolbarComponent,
        isQueryList: true,
      },
      {
        property: "paginationComponents",
        childType: IgxPaginatorComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "groupsRecords", writable: true },
      { name: "filteredData", writable: true },
      { name: "totalItemCount", writable: true },
      { name: "groupsRowList" },
      { name: "groupAreaTemplate", writable: true },
      { name: "hasGroupableColumns" },
      { name: "dropAreaVisible" },
      { name: "selectedCells" },
      { name: "hasColumnsToAutosize" },
      { name: "headerGroups" },
      { name: "actionStrip", writable: true },
      { name: "emptyFilteredGridTemplate", writable: true },
      { name: "emptyGridDefaultTemplate", writable: true },
      { name: "headerContainer" },
      { name: "headerSelectorContainer" },
      { name: "headerDragContainer" },
      { name: "headerGroupContainer" },
      { name: "filteringRow" },
      { name: "rowExpandedIndicatorTemplate", writable: true },
      { name: "rowCollapsedIndicatorTemplate", writable: true },
      { name: "headerExpandIndicatorTemplate", writable: true },
      { name: "headerCollapseIndicatorTemplate", writable: true },
      { name: "excelStyleHeaderIconDirectiveTemplate", writable: true },
      { name: "sortDescendingHeaderIconDirectiveTemplate", writable: true },
      { name: "dragRowID", writable: true },
      { name: "headerWidth" },
      { name: "shouldGenerate", writable: true },
      { name: "headerGroupsList" },
      { name: "headerCellList" },
      { name: "filterCellList" },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "activeDescendant" },
      { name: "bannerClass" },
      { name: "hiddenColumnsCount" },
      { name: "pinnedColumnsCount" },
      { name: "transactions" },
      { name: "isPivot", writable: true },
      { name: "filteredSortedData" },
      { name: "validation", writable: true },
      { name: "selectionService", writable: true },
      { name: "colResizingService", writable: true },
      { name: "gridAPI", writable: true },
      { name: "document", writable: true },
      { name: "cdr", writable: true },
      { name: "navigation", writable: true },
      { name: "filteringService", writable: true },
      { name: "summaryService", writable: true },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "defaultHeaderGroupMinWidth" },
      { name: "pinnedWidth" },
      { name: "unpinnedWidth" },
      { name: "pinnedColumns" },
      { name: "pinnedRows" },
      { name: "unpinnedColumns" },
      { name: "visibleColumns" },
      { name: "totalPages" },
      { name: "isFirstPage" },
      { name: "isLastPage" },
      { name: "totalWidth" },
      { name: "pinnedRowHeight" },
      { name: "totalHeight" },
      { name: "hasSortableColumns" },
      { name: "hasEditableColumns" },
      { name: "hasFilterableColumns" },
      { name: "hasSummarizedColumns" },
      { name: "hasMovableColumns" },
      { name: "hasColumnGroups" },
      { name: "hasColumnLayouts" },
      { name: "pinnedDataView" },
      { name: "unpinnedDataView" },
      { name: "dataView" },
    ],
    methods: [
      "getCellByColumnVisibleIndex",
      "groupBy",
      "clearGrouping",
      "isExpandedGroup",
      "toggleGroup",
      "selectRowsInGroup",
      "deselectRowsInGroup",
      "fullyExpandGroup",
      "toggleAllGroupRows",
      "getSelectedData",
      "getRowByIndex",
      "getRowByKey",
      "getCellByColumn",
      "getCellByKey",
      "pinRow",
      "unpinRow",
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandAll",
      "collapseAll",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "nextPage",
      "previousPage",
      "moveColumn",
      "paginate",
      "markForCheck",
      "addRow",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "reflow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "selectRange",
      "getSelectedRanges",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "combineSelectedCellAndColumnData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
      "beginAddRowByIndex",
    ],
    templateProps: [
      "dropAreaTemplate",
      "detailTemplate",
      "groupByRowSelectorTemplate",
      "groupRowTemplate",
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "snackbarDisplayTime",
      "summaryRowHeight",
      "page",
      "perPage",
      "totalRecords",
    ],
    boolProps: [
      "groupsExpanded",
      "hideGroupedColumns",
      "showGroupArea",
      "autoGenerate",
      "moving",
      "paging",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "batchEditing",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxRowIslandComponent,
    parents: [IgxHierarchicalGridComponent, IgxRowIslandComponent],
    contentQueries: [
      {
        property: "children",
        childType: IgxRowIslandComponent,
        isQueryList: true,
      },
      {
        property: "childColumns",
        childType: IgxColumnComponent,
        isQueryList: true,
      },
      {
        property: "actionStrips",
        childType: IgxActionStripComponent,
        isQueryList: true,
      },
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      { property: "actionStrip", childType: IgxActionStripComponent },
    ],
    additionalProperties: [
      { name: "islandToolbarTemplate", writable: true },
      { name: "islandPaginatorTemplate", writable: true },
      { name: "actionStrips", writable: true },
      { name: "data" },
      { name: "filteredData" },
      { name: "selectionService", writable: true },
      { name: "colResizingService", writable: true },
      { name: "document", writable: true },
      { name: "summaryService", writable: true },
      { name: "rowIslandAPI", writable: true },
      { name: "gridAPI", writable: true },
      { name: "hasColumnsToAutosize" },
      { name: "headerGroups" },
      { name: "actionStrip", writable: true },
      { name: "emptyFilteredGridTemplate", writable: true },
      { name: "emptyGridDefaultTemplate", writable: true },
      { name: "headerContainer" },
      { name: "headerSelectorContainer" },
      { name: "headerDragContainer" },
      { name: "headerGroupContainer" },
      { name: "filteringRow" },
      { name: "rowExpandedIndicatorTemplate", writable: true },
      { name: "rowCollapsedIndicatorTemplate", writable: true },
      { name: "headerExpandIndicatorTemplate", writable: true },
      { name: "headerCollapseIndicatorTemplate", writable: true },
      { name: "excelStyleHeaderIconDirectiveTemplate", writable: true },
      { name: "sortDescendingHeaderIconDirectiveTemplate", writable: true },
      { name: "dragRowID", writable: true },
      { name: "headerWidth" },
      { name: "shouldGenerate", writable: true },
      { name: "headerGroupsList" },
      { name: "headerCellList" },
      { name: "filterCellList" },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "activeDescendant" },
      { name: "bannerClass" },
      { name: "hiddenColumnsCount" },
      { name: "pinnedColumnsCount" },
      { name: "transactions" },
      { name: "isPivot", writable: true },
      { name: "filteredSortedData" },
      { name: "validation", writable: true },
      { name: "cdr", writable: true },
      { name: "navigation", writable: true },
      { name: "filteringService", writable: true },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "defaultHeaderGroupMinWidth" },
      { name: "pinnedWidth" },
      { name: "unpinnedWidth" },
      { name: "pinnedColumns" },
      { name: "pinnedRows" },
      { name: "unpinnedColumns" },
      { name: "visibleColumns" },
      { name: "totalPages" },
      { name: "isFirstPage" },
      { name: "isLastPage" },
      { name: "totalWidth" },
      { name: "pinnedRowHeight" },
      { name: "totalHeight" },
      { name: "hasSortableColumns" },
      { name: "hasEditableColumns" },
      { name: "hasFilterableColumns" },
      { name: "hasSummarizedColumns" },
      { name: "hasMovableColumns" },
      { name: "hasColumnGroups" },
      { name: "hasColumnLayouts" },
      { name: "pinnedDataView" },
      { name: "unpinnedDataView" },
      { name: "dataView" },
    ],
    methods: [
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandAll",
      "collapseAll",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "nextPage",
      "previousPage",
      "moveColumn",
      "paginate",
      "markForCheck",
      "addRow",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "pinRow",
      "unpinRow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "selectRange",
      "getSelectedRanges",
      "getSelectedData",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "combineSelectedCellAndColumnData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
      "beginAddRowByIndex",
    ],
    templateProps: [
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "snackbarDisplayTime",
      "summaryRowHeight",
      "page",
      "perPage",
      "totalRecords",
    ],
    boolProps: [
      "expandChildren",
      "showExpandAll",
      "autoGenerate",
      "moving",
      "paging",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxHierarchicalGridComponent,
    parents: [],
    contentQueries: [
      {
        property: "childLayoutList",
        childType: IgxRowIslandComponent,
        isQueryList: true,
      },
      {
        property: "allLayoutList",
        childType: IgxRowIslandComponent,
        isQueryList: true,
        descendants: true,
      },
      {
        property: "paginatorList",
        childType: IgxPaginatorComponent,
        isQueryList: true,
        descendants: true,
      },
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      { property: "actionStrip", childType: IgxActionStripComponent },
      {
        property: "toolbar",
        childType: IgxGridToolbarComponent,
        isQueryList: true,
      },
      {
        property: "paginationComponents",
        childType: IgxPaginatorComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "toolbarTemplate", writable: true },
      { name: "toolbarOutlet", writable: true },
      { name: "paginatorOutlet", writable: true },
      { name: "filteredData", writable: true },
      { name: "totalItemCount", writable: true },
      { name: "foreignKey" },
      { name: "outletDirective" },
      { name: "selectedCells" },
      { name: "selectionService", writable: true },
      { name: "colResizingService", writable: true },
      { name: "gridAPI", writable: true },
      { name: "document", writable: true },
      { name: "summaryService", writable: true },
      { name: "hasColumnsToAutosize" },
      { name: "headerGroups" },
      { name: "actionStrip", writable: true },
      { name: "emptyFilteredGridTemplate", writable: true },
      { name: "emptyGridDefaultTemplate", writable: true },
      { name: "headerContainer" },
      { name: "headerSelectorContainer" },
      { name: "headerDragContainer" },
      { name: "headerGroupContainer" },
      { name: "filteringRow" },
      { name: "rowExpandedIndicatorTemplate", writable: true },
      { name: "rowCollapsedIndicatorTemplate", writable: true },
      { name: "headerExpandIndicatorTemplate", writable: true },
      { name: "headerCollapseIndicatorTemplate", writable: true },
      { name: "excelStyleHeaderIconDirectiveTemplate", writable: true },
      { name: "sortDescendingHeaderIconDirectiveTemplate", writable: true },
      { name: "dragRowID", writable: true },
      { name: "headerWidth" },
      { name: "shouldGenerate", writable: true },
      { name: "headerGroupsList" },
      { name: "headerCellList" },
      { name: "filterCellList" },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "activeDescendant" },
      { name: "bannerClass" },
      { name: "hiddenColumnsCount" },
      { name: "pinnedColumnsCount" },
      { name: "transactions" },
      { name: "isPivot", writable: true },
      { name: "filteredSortedData" },
      { name: "validation", writable: true },
      { name: "cdr", writable: true },
      { name: "navigation", writable: true },
      { name: "filteringService", writable: true },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "defaultHeaderGroupMinWidth" },
      { name: "pinnedWidth" },
      { name: "unpinnedWidth" },
      { name: "pinnedColumns" },
      { name: "pinnedRows" },
      { name: "unpinnedColumns" },
      { name: "visibleColumns" },
      { name: "totalPages" },
      { name: "isFirstPage" },
      { name: "isLastPage" },
      { name: "totalWidth" },
      { name: "pinnedRowHeight" },
      { name: "totalHeight" },
      { name: "hasSortableColumns" },
      { name: "hasEditableColumns" },
      { name: "hasFilterableColumns" },
      { name: "hasSummarizedColumns" },
      { name: "hasMovableColumns" },
      { name: "hasColumnGroups" },
      { name: "hasColumnLayouts" },
      { name: "pinnedDataView" },
      { name: "unpinnedDataView" },
      { name: "dataView" },
    ],
    methods: [
      "getCellByColumnVisibleIndex",
      "getRowByIndex",
      "getRowByKey",
      "getCellByColumn",
      "getCellByKey",
      "pinRow",
      "unpinRow",
      "ngOnDestroy",
      "getDefaultExpandState",
      "onContainerScroll",
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandAll",
      "collapseAll",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "nextPage",
      "previousPage",
      "moveColumn",
      "paginate",
      "markForCheck",
      "addRow",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "reflow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "selectRange",
      "getSelectedRanges",
      "getSelectedData",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "combineSelectedCellAndColumnData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
      "beginAddRowByIndex",
    ],
    templateProps: [
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "snackbarDisplayTime",
      "summaryRowHeight",
      "page",
      "perPage",
      "totalRecords",
    ],
    boolProps: [
      "expandChildren",
      "showExpandAll",
      "autoGenerate",
      "moving",
      "paging",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxPivotGridComponent,
    parents: [],
    contentQueries: [
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      {
        property: "toolbar",
        childType: IgxGridToolbarComponent,
        isQueryList: true,
      },
      {
        property: "paginationComponents",
        childType: IgxPaginatorComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "dimensionsSortingExpressions" },
      { name: "columnGroupStates", writable: true },
      { name: "dimensionDataColumns", writable: true },
      { name: "pivotKeys" },
      { name: "isPivot", writable: true },
      { name: "emptyRowDimension" },
      { name: "defaultRowHeight" },
      { name: "selectionService", writable: true },
      { name: "colResizingService", writable: true },
      { name: "document", writable: true },
      { name: "summaryService", writable: true },
      { name: "allDimensions" },
      { name: "filteredData", writable: true },
      { name: "pivotContentCalcWidth" },
      { name: "pivotPinnedWidth" },
      { name: "pivotUnpinnedWidth" },
      { name: "rowDimensions" },
      { name: "columnDimensions" },
      { name: "filterDimensions" },
      { name: "values" },
      { name: "hasColumnsToAutosize" },
      { name: "headerGroups" },
      { name: "emptyFilteredGridTemplate", writable: true },
      { name: "emptyGridDefaultTemplate", writable: true },
      { name: "headerContainer" },
      { name: "headerSelectorContainer" },
      { name: "headerDragContainer" },
      { name: "headerGroupContainer" },
      { name: "filteringRow" },
      { name: "rowExpandedIndicatorTemplate", writable: true },
      { name: "rowCollapsedIndicatorTemplate", writable: true },
      { name: "headerExpandIndicatorTemplate", writable: true },
      { name: "headerCollapseIndicatorTemplate", writable: true },
      { name: "excelStyleHeaderIconDirectiveTemplate", writable: true },
      { name: "sortDescendingHeaderIconDirectiveTemplate", writable: true },
      { name: "headerWidth" },
      { name: "headerGroupsList" },
      { name: "headerCellList" },
      { name: "filterCellList" },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "activeDescendant" },
      { name: "bannerClass" },
      { name: "filteredSortedData" },
      { name: "validation", writable: true },
      { name: "gridAPI", writable: true },
      { name: "cdr", writable: true },
      { name: "navigation", writable: true },
      { name: "filteringService", writable: true },
      { name: "nativeElement" },
      { name: "defaultHeaderGroupMinWidth" },
      { name: "visibleColumns" },
      { name: "totalWidth" },
      { name: "hasSortableColumns" },
      { name: "hasFilterableColumns" },
      { name: "hasColumnGroups" },
      { name: "hasColumnLayouts" },
      { name: "dataView" },
    ],
    methods: [
      "notifyDimensionChange",
      "toggleColumn",
      "getColumnGroupExpandState",
      "toggleRowGroup",
      "autoSizeRowDimension",
      "insertDimensionAt",
      "moveDimension",
      "removeDimension",
      "toggleDimension",
      "insertValueAt",
      "moveValue",
      "removeValue",
      "toggleValue",
      "sortDimension",
      "filterDimension",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "markForCheck",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "clearFilter",
      "clearSort",
      "reflow",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "selectRange",
      "getSelectedRanges",
      "getSelectedData",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "combineSelectedCellAndColumnData",
      "navigateTo",
    ],
    templateProps: [
      "valueChipTemplate",
      "emptyPivotGridTemplate",
      "emptyGridTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
    ],
    boolProps: [
      "showPivotConfigurationUI",
      "superCompactMode",
      "defaultExpandState",
      "isLoading",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxColumnLayoutComponent,
    parents: [IgxGridComponent],
    contentQueries: [
      {
        property: "children",
        childType: IgxColumnComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "childrenVisibleIndexes", writable: true },
      { name: "width", writable: true },
      { name: "columnLayout" },
      { name: "visibleIndex" },
      { name: "hasLastPinnedChildColumn" },
      { name: "hasFirstPinnedChildColumn" },
      { name: "cells" },
      { name: "selected", writable: true },
      { name: "allChildren" },
      { name: "columnGroup" },
      { name: "autoSize", writable: true },
      { name: "calcPixelWidth", writable: true },
      { name: "index" },
      { name: "defaultMinWidth" },
      { name: "columnLayoutChild" },
      { name: "level" },
      { name: "isLastPinned" },
      { name: "isFirstPinned" },
      { name: "rightPinnedOffset" },
      { name: "gridRowSpan" },
      { name: "gridColumnSpan" },
      { name: "defaultWidth", writable: true },
      { name: "widthSetByUser", writable: true },
      { name: "filteringExpressionsTree" },
      { name: "parent", writable: true },
      { name: "grid", writable: true },
      { name: "cdr", writable: true },
      { name: "topLevelParent" },
      { name: "headerCell" },
      { name: "filterCell" },
      { name: "headerGroup" },
    ],
    methods: [
      "getInitialChildColumnSizes",
      "getFilledChildColumnSizes",
      "getResizableColUnderEnd",
      "pin",
      "unpin",
      "move",
      "autosize",
    ],
    templateProps: [
      "collapsibleIndicatorTemplate",
      "summaryTemplate",
      "headerTemplate",
      "errorTemplate",
      "filterCellTemplate",
    ],
    numericProps: ["rowEnd", "colEnd", "rowStart", "colStart"],
    boolProps: [
      "hidden",
      "collapsible",
      "expanded",
      "searchable",
      "sortable",
      "groupable",
      "editable",
      "filterable",
      "resizable",
      "autosizeHeader",
      "hasSummary",
      "disableHiding",
      "disablePinning",
      "movable",
      "filteringIgnoreCase",
      "sortingIgnoreCase",
      "pinned",
      "visibleWhenCollapsed",
    ],
    provideAs: IgxColumnComponent,
  },
  {
    component: IgxGridToolbarAdvancedFilteringComponent,
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [{ name: "grid" }],
    methods: [],
  },
  {
    component: IgxGridToolbarExporterComponent,
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [
      { name: "isExporting", writable: true },
      { name: "grid" },
    ],
    methods: ["export", "ngOnDestroy"],
    boolProps: ["exportCSV", "exportExcel"],
  },
  {
    component: IgxGridToolbarHidingComponent,
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [{ name: "grid" }],
    methods: ["checkAll", "uncheckAll", "ngOnDestroy"],
    numericProps: ["indentetion"],
    boolProps: ["hideFilter"],
  },
  {
    component: IgxGridToolbarPinningComponent,
    parents: [IgxGridToolbarComponent],
    contentQueries: [],
    additionalProperties: [{ name: "grid" }],
    methods: ["checkAll", "uncheckAll", "ngOnDestroy"],
    numericProps: ["indentetion"],
    boolProps: ["hideFilter"],
  },
  {
    component: IgxTreeGridComponent,
    parents: [],
    contentQueries: [
      {
        property: "columnList",
        childType: IgxColumnComponent,
        isQueryList: true,
        descendants: true,
      },
      { property: "actionStrip", childType: IgxActionStripComponent },
      {
        property: "toolbar",
        childType: IgxGridToolbarComponent,
        isQueryList: true,
      },
      {
        property: "paginationComponents",
        childType: IgxPaginatorComponent,
        isQueryList: true,
      },
    ],
    additionalProperties: [
      { name: "rootRecords", writable: true },
      { name: "records", writable: true },
      { name: "processedRootRecords", writable: true },
      { name: "processedRecords", writable: true },
      { name: "filteredData", writable: true },
      { name: "selectionService", writable: true },
      { name: "colResizingService", writable: true },
      { name: "gridAPI", writable: true },
      { name: "document", writable: true },
      { name: "cdr", writable: true },
      { name: "navigation", writable: true },
      { name: "filteringService", writable: true },
      { name: "summaryService", writable: true },
      { name: "selectedCells" },
      { name: "hasGroupableColumns" },
      { name: "hasColumnsToAutosize" },
      { name: "headerGroups" },
      { name: "actionStrip", writable: true },
      { name: "emptyFilteredGridTemplate", writable: true },
      { name: "emptyGridDefaultTemplate", writable: true },
      { name: "headerContainer" },
      { name: "headerSelectorContainer" },
      { name: "headerDragContainer" },
      { name: "headerGroupContainer" },
      { name: "filteringRow" },
      { name: "rowExpandedIndicatorTemplate", writable: true },
      { name: "rowCollapsedIndicatorTemplate", writable: true },
      { name: "headerExpandIndicatorTemplate", writable: true },
      { name: "headerCollapseIndicatorTemplate", writable: true },
      { name: "excelStyleHeaderIconDirectiveTemplate", writable: true },
      { name: "sortDescendingHeaderIconDirectiveTemplate", writable: true },
      { name: "dragRowID", writable: true },
      { name: "headerWidth" },
      { name: "shouldGenerate", writable: true },
      { name: "headerGroupsList" },
      { name: "headerCellList" },
      { name: "filterCellList" },
      { name: "rowList" },
      { name: "dataRowList" },
      { name: "activeDescendant" },
      { name: "bannerClass" },
      { name: "hiddenColumnsCount" },
      { name: "pinnedColumnsCount" },
      { name: "isPivot", writable: true },
      { name: "filteredSortedData" },
      { name: "validation", writable: true },
      { name: "nativeElement" },
      { name: "defaultRowHeight" },
      { name: "defaultHeaderGroupMinWidth" },
      { name: "pinnedWidth" },
      { name: "unpinnedWidth" },
      { name: "pinnedColumns" },
      { name: "pinnedRows" },
      { name: "unpinnedColumns" },
      { name: "visibleColumns" },
      { name: "totalPages" },
      { name: "isFirstPage" },
      { name: "isLastPage" },
      { name: "totalWidth" },
      { name: "pinnedRowHeight" },
      { name: "totalHeight" },
      { name: "hasSortableColumns" },
      { name: "hasEditableColumns" },
      { name: "hasFilterableColumns" },
      { name: "hasSummarizedColumns" },
      { name: "hasMovableColumns" },
      { name: "hasColumnGroups" },
      { name: "hasColumnLayouts" },
      { name: "pinnedDataView" },
      { name: "unpinnedDataView" },
      { name: "dataView" },
    ],
    methods: [
      "getCellByColumnVisibleIndex",
      "ngDoCheck",
      "getDefaultExpandState",
      "expandAll",
      "collapseAll",
      "addRow",
      "beginAddRowByIndex",
      "getSelectedData",
      "getRowByIndex",
      "getRowByKey",
      "getCellByColumn",
      "getCellByKey",
      "pinRow",
      "unpinRow",
      "isRecordPinnedByIndex",
      "toggleColumnVisibility",
      "expandRow",
      "collapseRow",
      "toggleRow",
      "getHeaderGroupWidth",
      "getColumnByName",
      "getColumnByVisibleIndex",
      "recalculateAutoSizes",
      "nextPage",
      "previousPage",
      "moveColumn",
      "paginate",
      "markForCheck",
      "deleteRow",
      "updateCell",
      "updateRow",
      "getRowData",
      "sort",
      "filter",
      "filterGlobal",
      "enableSummaries",
      "disableSummaries",
      "clearFilter",
      "clearSort",
      "pinColumn",
      "unpinColumn",
      "reflow",
      "findNext",
      "findPrev",
      "refreshSearch",
      "clearSearch",
      "getPinnedWidth",
      "selectRows",
      "deselectRows",
      "selectAllRows",
      "deselectAllRows",
      "selectRange",
      "getSelectedRanges",
      "selectedColumns",
      "selectColumns",
      "deselectColumns",
      "deselectAllColumns",
      "selectAllColumns",
      "getSelectedColumnsData",
      "combineSelectedCellAndColumnData",
      "navigateTo",
      "getNextCell",
      "getPreviousCell",
      "openAdvancedFilteringDialog",
      "closeAdvancedFilteringDialog",
      "endEdit",
      "beginAddRowById",
    ],
    templateProps: [
      "rowLoadingIndicatorTemplate",
      "emptyGridTemplate",
      "addRowEmptyTemplate",
      "loadingGridTemplate",
      "dragGhostCustomTemplate",
      "rowEditTextTemplate",
      "rowAddTextTemplate",
      "rowEditActionsTemplate",
      "excelStyleHeaderIconTemplate",
      "sortAscendingHeaderIconTemplate",
      "sortDescendingHeaderIconTemplate",
      "sortHeaderIconTemplate",
      "headSelectorTemplate",
      "rowSelectorTemplate",
      "dragIndicatorIconTemplate",
    ],
    numericProps: [
      "expansionDepth",
      "snackbarDisplayTime",
      "summaryRowHeight",
      "page",
      "perPage",
      "totalRecords",
    ],
    boolProps: [
      "cascadeOnDelete",
      "autoGenerate",
      "moving",
      "paging",
      "hideRowSelectors",
      "rowDraggable",
      "rowEditable",
      "isLoading",
      "allowFiltering",
      "allowAdvancedFiltering",
      "showSummaryOnCollapse",
      "batchEditing",
      "selectRowOnClick",
    ],
  },
  {
    component: IgxPivotDataSelectorComponent,
    parents: [],
    contentQueries: [],
    additionalProperties: [{ name: "animationSettings", writable: true }],
    methods: [],
    boolProps: [
      "columnsExpanded",
      "rowsExpanded",
      "filtersExpanded",
      "valuesExpanded",
    ],
  },
];
