import { ViewChild } from '@angular/core';
import { IgxExcelExporterService } from './excel-exporter';
import { IgxGridModule } from '../../grid';
import { IgxColumnComponent } from '../../grid/column.component';
import { IgxGridComponent } from '../../grid/grid.component';
import { ValueData } from './test-data.service';

describe('Excel Exporter', () => {

});

export class GridAutogeneratedColumnsComponent {

    @ViewChild(IgxGridComponent, { read: IgxGridComponent })
    public instance: IgxGridComponent;
}