import { AnimationReferenceMetadata } from "@angular/animations";
declare const flipTop: AnimationReferenceMetadata;
declare const flipBottom: AnimationReferenceMetadata;
declare const flipLeft: AnimationReferenceMetadata;
declare const flipRight: AnimationReferenceMetadata;
declare const flipHorFwd: AnimationReferenceMetadata;
declare const flipHorBck: AnimationReferenceMetadata;
declare const flipVerFwd: AnimationReferenceMetadata;
declare const flipVerBck: AnimationReferenceMetadata;
export { flipTop, flipRight, flipBottom, flipLeft, flipHorFwd, flipHorBck, flipVerFwd, flipVerBck };
