import { NgModule } from '@angular/core';
import {
    IgxAutocompleteModule,
    IgxAvatarModule,
    IgxBadgeModule,
    IgxBottomNavModule,
    IgxButtonGroupModule,
    IgxButtonModule,
    IgxCalendarModule,
    IgxBannerModule,
    IgxCardModule,
    IgxCarouselModule,
    IgxCheckboxModule,
    IgxChipsModule,
    IgxComboModule,
    IgxDatePickerModule,
    IgxDialogModule,
    IgxDropDownModule,
    IgxExpansionPanelModule,
    IgxFilterModule,
    IgxFocusModule,
    IgxForOfModule,
    IgxInputGroupModule,
    IgxLayoutModule,
    IgxListModule,
    IgxMaskModule,
    IgxNavbarModule,
    IgxNavigationDrawerModule,
    IgxProgressBarModule,
    IgxRadioModule,
    IgxRippleModule,
    IgxSliderModule,
    IgxSnackbarModule,
    IgxSwitchModule,
    IgxTabsModule,
    IgxTimePickerModule,
    IgxToastModule,
    IgxToggleModule,
    IgxTooltipModule
} from 'igniteui-angular';

const igniteModules = [
    IgxAutocompleteModule,
    IgxAvatarModule,
    IgxBadgeModule,
    IgxBottomNavModule,
    IgxButtonGroupModule,
    IgxButtonModule,
    IgxCalendarModule,
    IgxBannerModule,
    IgxCardModule,
    IgxCarouselModule,
    IgxCheckboxModule,
    IgxChipsModule,
    IgxComboModule,
    IgxDatePickerModule,
    IgxDialogModule,
    IgxDropDownModule,
    IgxExpansionPanelModule,
    IgxFilterModule,
    IgxFocusModule,
    IgxForOfModule,
    IgxInputGroupModule,
    IgxLayoutModule,
    IgxListModule,
    IgxMaskModule,
    IgxNavbarModule,
    IgxNavigationDrawerModule,
    IgxProgressBarModule,
    IgxRadioModule,
    IgxRippleModule,
    IgxSliderModule,
    IgxSnackbarModule,
    IgxSwitchModule,
    IgxTabsModule,
    IgxTimePickerModule,
    IgxToastModule,
    IgxToggleModule,
    IgxTooltipModule
];

@NgModule({
    imports: igniteModules,
    exports: igniteModules
})
export class SharedModule {}
