import { AnimationReferenceMetadata } from "@angular/animations";
declare const rotateInCenter: AnimationReferenceMetadata;
declare const rotateOutCenter: AnimationReferenceMetadata;
declare const rotateInTop: AnimationReferenceMetadata;
declare const rotateOutTop: AnimationReferenceMetadata;
declare const rotateInRight: AnimationReferenceMetadata;
declare const rotateOutRight: AnimationReferenceMetadata;
declare const rotateInBottom: AnimationReferenceMetadata;
declare const rotateOutBottom: AnimationReferenceMetadata;
declare const rotateInLeft: AnimationReferenceMetadata;
declare const rotateOutLeft: AnimationReferenceMetadata;
declare const rotateInTr: AnimationReferenceMetadata;
declare const rotateOutTr: AnimationReferenceMetadata;
declare const rotateInBr: AnimationReferenceMetadata;
declare const rotateOutBr: AnimationReferenceMetadata;
declare const rotateInBl: AnimationReferenceMetadata;
declare const rotateOutBl: AnimationReferenceMetadata;
declare const rotateInTl: AnimationReferenceMetadata;
declare const rotateOutTl: AnimationReferenceMetadata;
declare const rotateInDiagonal1: AnimationReferenceMetadata;
declare const rotateOutDiagonal1: AnimationReferenceMetadata;
declare const rotateInDiagonal2: AnimationReferenceMetadata;
declare const rotateOutDiagonal2: AnimationReferenceMetadata;
declare const rotateInHor: AnimationReferenceMetadata;
declare const rotateOutHor: AnimationReferenceMetadata;
declare const rotateInVer: AnimationReferenceMetadata;
declare const rotateOutVer: AnimationReferenceMetadata;
export { rotateInCenter, rotateInTop, rotateInRight, rotateInLeft, rotateInBottom, rotateInTr, rotateInBr, rotateInBl, rotateInTl, rotateInDiagonal1, rotateInDiagonal2, rotateInHor, rotateInVer, rotateOutCenter, rotateOutTop, rotateOutRight, rotateOutLeft, rotateOutBottom, rotateOutTr, rotateOutBr, rotateOutBl, rotateOutTl, rotateOutDiagonal1, rotateOutDiagonal2, rotateOutHor, rotateOutVer };
