import { defineComponents } from './register';
import {
    IgcGridComponent,
    IgcTreeGridComponent,
    IgcHierarchicalGridComponent,
    IgcPivotGridComponent,
    IgcPivotDataSelectorComponent,
    IgcRowIslandComponent,
    IgcColumnGroupComponent,
    IgcColumnLayoutComponent,
    IgcColumnComponent,
    IgcPaginatorComponent,
    IgcGridToolbarComponent,
    IgcActionStripComponent,
    IgcGridStateComponent,
    IgcGridEditingActionsComponent,
    IgcGridPinningActionsComponent,
    IgcGridToolbarTitleComponent,
    IgcGridToolbarActionsComponent,
    IgcGridToolbarHidingComponent,
    IgcGridToolbarPinningComponent,
    IgcGridToolbarExporterComponent,
    IgcGridToolbarAdvancedFilteringComponent,
} from '../app/components';

export function defineAllComponents() {
  defineComponents(
    IgcGridComponent,
    IgcTreeGridComponent,
    IgcHierarchicalGridComponent,
    IgcPivotGridComponent,
    IgcPivotDataSelectorComponent,
    IgcRowIslandComponent,
    IgcColumnGroupComponent,
    IgcColumnLayoutComponent,
    IgcColumnComponent,
    IgcPaginatorComponent,
    IgcGridToolbarComponent,
    IgcActionStripComponent,
    IgcGridStateComponent,
    IgcGridEditingActionsComponent,
    IgcGridPinningActionsComponent,
    IgcGridToolbarTitleComponent,
    IgcGridToolbarActionsComponent,
    IgcGridToolbarHidingComponent,
    IgcGridToolbarPinningComponent,
    IgcGridToolbarExporterComponent,
    IgcGridToolbarAdvancedFilteringComponent,
  );
}
