import { AnimationReferenceMetadata } from "@angular/animations";
declare const slideInTop: AnimationReferenceMetadata;
declare const slideInLeft: AnimationReferenceMetadata;
declare const slideInRight: AnimationReferenceMetadata;
declare const slideInBottom: AnimationReferenceMetadata;
declare const slideInTr: AnimationReferenceMetadata;
declare const slideInTl: AnimationReferenceMetadata;
declare const slideInBr: AnimationReferenceMetadata;
declare const slideInBl: AnimationReferenceMetadata;
declare const slideOutTop: AnimationReferenceMetadata;
declare const slideOutRight: AnimationReferenceMetadata;
declare const slideOutBottom: AnimationReferenceMetadata;
declare const slideOutLeft: AnimationReferenceMetadata;
declare const slideOutTr: AnimationReferenceMetadata;
declare const slideOutBr: AnimationReferenceMetadata;
declare const slideOutBl: AnimationReferenceMetadata;
declare const slideOutTl: AnimationReferenceMetadata;
export { slideInTop, slideInRight, slideInBottom, slideInLeft, slideInTr, slideInBr, slideInBl, slideInTl, slideOutTop, slideOutBottom, slideOutRight, slideOutLeft, slideOutTr, slideOutBr, slideOutBl, slideOutTl };
