import { AnimationReferenceMetadata } from "@angular/animations";
declare const shakeHor: AnimationReferenceMetadata;
declare const shakeVer: AnimationReferenceMetadata;
declare const shakeTop: AnimationReferenceMetadata;
declare const shakeBottom: AnimationReferenceMetadata;
declare const shakeRight: AnimationReferenceMetadata;
declare const shakeLeft: AnimationReferenceMetadata;
declare const shakeCenter: AnimationReferenceMetadata;
declare const shakeTr: AnimationReferenceMetadata;
declare const shakeBr: AnimationReferenceMetadata;
declare const shakeBl: AnimationReferenceMetadata;
declare const shakeTl: AnimationReferenceMetadata;
export { shakeHor, shakeVer, shakeTop, shakeBottom, shakeRight, shakeLeft, shakeCenter, shakeTr, shakeBr, shakeBl, shakeTl };
