export const DATA = [
    {
        ID: 1,
        Name: 'John Doe',
        Age: 30,
        City: 'New York',
        Country: 'USA',
        Phone: '555-1234',
        Email: 'john.doe@example.com',
        Address: '123 Main St',
        PostalCode: '10001',
        Company: 'Example Inc.',
        JobTitle: 'Software Engineer',
        Salary: 85000,
        HireDate: '2020-01-15',
        IsActive: true
    },
    {
        ID: 2,
        Name: 'Jane Smith',
        Age: 25,
        City: 'London',
        Country: 'UK',
        Phone: '555-5678',
        Email: 'jane.smith@example.com',
        Address: '456 Oxford St',
        PostalCode: 'W1D 1LL',
        Company: 'UK Tech',
        JobTitle: 'Designer',
        Salary: 75000,
        HireDate: '2021-03-22',
        IsActive: true
    },
    {
        ID: 3,
        Name: 'Bob Johnson',
        Age: 45,
        City: 'Paris',
        Country: 'France',
        Phone: '555-9012',
        Email: 'bob.johnson@example.com',
        Address: '789 Rue de Rivoli',
        PostalCode: '75001',
        Company: 'France Solutions',
        JobTitle: 'Manager',
        Salary: 95000,
        HireDate: '2019-06-10',
        IsActive: false
    },
    {
        ID: 4,
        Name: 'Alice Williams',
        Age: 35,
        City: 'Berlin',
        Country: 'Germany',
        Phone: '555-3456',
        Email: 'alice.williams@example.com',
        Address: '101 Unter den Linden',
        PostalCode: '10117',
        Company: 'Berlin App',
        JobTitle: 'Developer',
        Salary: 82000,
        HireDate: '2022-11-01',
        IsActive: true
    },
    {
        ID: 5,
        Name: 'Charlie Brown',
        Age: 28,
        City: 'Tokyo',
        Country: 'Japan',
        Phone: '555-7890',
        Email: 'charlie.brown@example.com',
        Address: '202 Shibuya Crossing',
        PostalCode: '150-0042',
        Company: 'Tokyo Systems',
        JobTitle: 'Analyst',
        Salary: 78000,
        HireDate: '2023-01-20',
        IsActive: true
    },
    {
        ID: 6,
        Name: 'Diana Prince',
        Age: 32,
        City: 'Themyscira',
        Country: 'Amazon',
        Phone: '555-1111',
        Email: 'diana.prince@example.com',
        Address: '1 Paradise Island',
        PostalCode: '00000',
        Company: 'Justice League',
        JobTitle: 'Warrior',
        Salary: 120000,
        HireDate: '1941-12-01',
        IsActive: true
    },
    {
        ID: 7,
        Name: 'Edward Elric',
        Age: 18,
        City: 'Resembool',
        Country: 'Amestris',
        Phone: '555-2222',
        Email: 'edward.elric@example.com',
        Address: 'Alchemist Way',
        PostalCode: 'A1B 2C3',
        Company: 'State Military',
        JobTitle: 'State Alchemist',
        Salary: 60000,
        HireDate: '2015-05-15',
        IsActive: true
    },
    {
        ID: 8,
        Name: 'Fiona Gallagher',
        Age: 24,
        City: 'Chicago',
        Country: 'USA',
        Phone: '555-3333',
        Email: 'fiona.gallagher@example.com',
        Address: 'South Side 21',
        PostalCode: '60601',
        Company: 'Self Employed',
        JobTitle: 'Entrepreneur',
        Salary: 45000,
        HireDate: '2018-09-12',
        IsActive: true
    },
    {
        ID: 9,
        Name: 'George Costanza',
        Age: 40,
        City: 'New York',
        Country: 'USA',
        Phone: '555-4444',
        Email: 'george.costanza@example.com',
        Address: 'Upper West Side',
        PostalCode: '10023',
        Company: 'Vandelay Industries',
        JobTitle: 'Architect',
        Salary: 55000,
        HireDate: '1990-05-15',
        IsActive: false
    },
    {
        ID: 10,
        Name: 'Hannah Abbott',
        Age: 22,
        City: 'Hogsmeade',
        Country: 'UK',
        Phone: '555-5555',
        Email: 'hannah.abbott@example.com',
        Address: 'The Leaky Cauldron',
        PostalCode: 'HP1 1AA',
        Company: 'Magic World',
        JobTitle: 'Barmaid',
        Salary: 35000,
        HireDate: '2016-09-01',
        IsActive: true
    },
    {
        ID: 11,
        Name: 'Ian Wright',
        Age: 58,
        City: 'London',
        Country: 'UK',
        Phone: '555-6666',
        Email: 'ian.wright@example.com',
        Address: 'Highbury Fields',
        PostalCode: 'N5 1AA',
        Company: 'Arsenal FC',
        JobTitle: 'Commentator',
        Salary: 150000,
        HireDate: '1980-08-01',
        IsActive: true
    },
    {
        ID: 12,
        Name: 'Julia Roberts',
        Age: 54,
        City: 'Los Angeles',
        Country: 'USA',
        Phone: '555-7777',
        Email: 'julia.roberts@example.com',
        Address: 'Malibu Beach',
        PostalCode: '90265',
        Company: 'Hollywood Inc.',
        JobTitle: 'Actress',
        Salary: 5000000,
        HireDate: '1987-01-01',
        IsActive: true
    },
    {
        ID: 13,
        Name: 'Kevin Hart',
        Age: 42,
        City: 'Philadelphia',
        Country: 'USA',
        Phone: '555-8888',
        Email: 'kevin.hart@example.com',
        Address: 'Brotherly Love Ave',
        PostalCode: '19101',
        Company: 'HartBeat Prod.',
        JobTitle: 'Comedian',
        Salary: 2000000,
        HireDate: '2001-01-01',
        IsActive: true
    },
    {
        ID: 14,
        Name: 'Laura Palmer',
        Age: 18,
        City: 'Twin Peaks',
        Country: 'USA',
        Phone: '555-9999',
        Email: 'laura.palmer@example.com',
        Address: 'Ghost Wood Forest',
        PostalCode: '98065',
        Company: 'Unknown',
        JobTitle: 'Student',
        Salary: 0,
        HireDate: '1989-02-24',
        IsActive: false
    },
    {
        ID: 15,
        Name: 'Michael Scott',
        Age: 45,
        City: 'Scranton',
        Country: 'USA',
        Phone: '555-0000',
        Email: 'michael.scott@example.com',
        Address: 'Dunder Mifflin Way',
        PostalCode: '18501',
        Company: 'Dunder Mifflin',
        JobTitle: 'Regional Manager',
        Salary: 65000,
        HireDate: '1992-01-15',
        IsActive: true
    },
    {
        ID: 16,
        Name: 'Nina Williams',
        Age: 32,
        City: 'Dublin',
        Country: 'Ireland',
        Phone: '555-1212',
        Email: 'nina.williams@example.com',
        Address: 'Emerald Isle',
        PostalCode: 'D1',
        Company: 'Tekken Corp',
        JobTitle: 'Assassin',
        Salary: 100000,
        HireDate: '1994-12-09',
        IsActive: true
    },
    {
        ID: 17,
        Name: 'Oscar Martinez',
        Age: 40,
        City: 'Scranton',
        Country: 'USA',
        Phone: '555-2323',
        Email: 'oscar.martinez@example.com',
        Address: 'Accounting Lane',
        PostalCode: '18502',
        Company: 'Dunder Mifflin',
        JobTitle: 'Accountant',
        Salary: 55000,
        HireDate: '1999-03-24',
        IsActive: true
    },
    {
        ID: 18,
        Name: 'Pam Beesly',
        Age: 30,
        City: 'Scranton',
        Country: 'USA',
        Phone: '555-3434',
        Email: 'pam.beesly@example.com',
        Address: 'Art Studio St',
        PostalCode: '18503',
        Company: 'Dunder Mifflin',
        JobTitle: 'Receptionist',
        Salary: 40000,
        HireDate: '2001-05-10',
        IsActive: true
    },
    {
        ID: 19,
        Name: 'Quentin Tarantino',
        Age: 58,
        City: 'Knoxville',
        Country: 'USA',
        Phone: '555-4545',
        Email: 'quentin.tarantino@example.com',
        Address: 'Film Noir Blvd',
        PostalCode: '37901',
        Company: 'Miramax',
        JobTitle: 'Director',
        Salary: 1000000,
        HireDate: '1992-01-21',
        IsActive: true
    },
    {
        ID: 20,
        Name: 'Riley Reid',
        Age: 30,
        City: 'Miami',
        Country: 'USA',
        Phone: '555-5656',
        Email: 'riley.reid@example.com',
        Address: 'South Beach',
        PostalCode: '33139',
        Company: 'Self',
        JobTitle: 'Influencer',
        Salary: 300000,
        HireDate: '2010-01-01',
        IsActive: true
    },
    {
        ID: 21,
        Name: 'Samwise Gamgee',
        Age: 38,
        City: 'Hobbiton',
        Country: 'Shire',
        Phone: '555-0011',
        Email: 'sam@fellowship.com',
        Address: 'Bagshot Row',
        PostalCode: 'SH1 1AA',
        Company: 'Gardeners Ltd',
        JobTitle: 'Head Gardener',
        Salary: 30000,
        HireDate: '1418-01-01',
        IsActive: true
    },
    {
        ID: 22,
        Name: 'Frodo Baggins',
        Age: 50,
        City: 'Hobbiton',
        Country: 'Shire',
        Phone: '555-0022',
        Email: 'frodo@fellowship.com',
        Address: 'Bag End',
        PostalCode: 'SH1 1BB',
        Company: 'Wealthy Hobbit',
        JobTitle: 'Ring Bearer',
        Salary: 0,
        HireDate: '1401-09-22',
        IsActive: false
    }
];
