import { ColumnType } from 'igniteui-angular/core/src/data-operations/grid-types';
import { IBaseEventArgs } from 'igniteui-angular/core/src/core/utils';

export interface IColumnsAutoGeneratedEventArgs extends IBaseEventArgs {
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ColumnCollection */
    columns?: ColumnType[]
}
