import { ColumnType } from '../../../../igniteui-angular/src/lib/grids/common/grid.interface';
import { IBaseEventArgs } from 'igniteui-angular/src/lib/core/utils';

export interface IColumnsAutoGeneratedEventArgs extends IBaseEventArgs {
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ColumnCollection */
    columns?: ColumnType[]
}
