import { ColumnType, IBaseEventArgs } from 'igniteui-angular/core';

export interface IColumnsAutoGeneratedEventArgs extends IBaseEventArgs {
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ColumnCollection */
    columns?: ColumnType[]
}
