import {
    Component, ChangeDetectionStrategy, Output, EventEmitter,
    QueryList, ContentChildren, CUSTOM_ELEMENTS_SCHEMA
} from '@angular/core';
import { NgTemplateOutlet, NgClass, NgStyle } from '@angular/common';
import {
    IGX_GRID_BASE,
    IGX_GRID_SERVICE_BASE,
    IgxColumnMovingDropDirective,
    IgxColumnResizingService,
    IgxFilteringService,
    IgxGridAddRowPipe,
    IgxGridBodyDirective,
    IgxGridColumnResizerComponent,
    IgxGridCRUDService,
    IgxGridDragSelectDirective,
    IgxGridHeaderRowComponent,
    IgxGridNavigationService,
    IgxGridRowClassesPipe,
    IgxGridRowPinningPipe,
    IgxGridRowStylesPipe,
    IgxGridSelectionService,
    IgxGridSummaryService,
    IgxGridTransactionPipe,
    IgxGridValidationService,
    IgxHasVisibleColumnsPipe,
    IgxRowEditTabStopDirective,
    IgxStringReplacePipe,
    IgxSummaryDataPipe,
    IgxSummaryRowComponent,
} from 'igniteui-angular/grids/core';
import { IgxGridAPIService } from 'igniteui-angular/grids/grid/src/grid-api.service';
import { IgxGridGroupByRowComponent } from 'igniteui-angular/grids/grid/src/groupby-row.component';
import { IgxGridGroupByAreaComponent } from 'igniteui-angular/grids/grid/src/grouping/grid-group-by-area.component';
import { IgxActionStripToken, IgxOverlayOutletDirective } from 'igniteui-angular/core';
import { IgxGridDetailsPipe } from 'igniteui-angular/grids/grid/src/grid.details.pipe';
import { IgxGridSummaryPipe } from 'igniteui-angular/grids/grid/src/grid.summary.pipe';
import { IgxGridGroupingPipe, IgxGridPagingPipe, IgxGridSortingPipe, IgxGridFilteringPipe, IgxGridCellMergePipe, IgxGridUnmergeActivePipe } from 'igniteui-angular/grids/grid/src/grid.pipes';
import { IgxGridRowComponent } from 'igniteui-angular/grids/grid/src/grid-row.component';
import { IgxButtonDirective, IgxForOfScrollSyncService, IgxForOfSyncService, IgxGridForOfDirective, IgxRippleDirective, IgxScrollInertiaDirective, IgxTemplateOutletDirective, IgxToggleDirective } from 'igniteui-angular/directives';
import { IgxCircularProgressBarComponent } from 'igniteui-angular/progressbar';
import { IgxSnackbarComponent } from 'igniteui-angular/snackbar';
import { IgxIconComponent } from 'igniteui-angular/icon';
import { IColumnsAutoGeneratedEventArgs } from './events';
import { IgxGridComponent } from 'igniteui-angular/grids/grid/src/grid.component';

/* blazorAdditionalDependency: Column */
/* blazorAdditionalDependency: ColumnGroup */
/* blazorAdditionalDependency: ColumnLayout */
/* blazorAdditionalDependency: GridToolbar */
/* blazorAdditionalDependency: GridToolbarActions */
/* blazorAdditionalDependency: GridToolbarTitle */
/* blazorAdditionalDependency: GridToolbarAdvancedFiltering */
/* blazorAdditionalDependency: GridToolbarExporter */
/* blazorAdditionalDependency: GridToolbarHiding */
/* blazorAdditionalDependency: GridToolbarPinning */
/* blazorAdditionalDependency: ActionStrip */
/* blazorAdditionalDependency: GridActionsBaseDirective */
/* blazorAdditionalDependency: GridEditingActions */
/* blazorAdditionalDependency: GridPinningActions */
/* blazorIndirectRender */
/**
 * Grid provides a way to present and manipulate tabular data.
 *
 * @igxModule IgxGridModule
 * @igxGroup Grids & Lists
 * @igxKeywords grid, table
 * @igxTheme igx-grid-theme
 * @remarks
 * The Ignite UI Grid is used for presenting and manipulating tabular data in the simplest way possible.  Once data
 * has been bound, it can be manipulated through filtering, sorting & editing operations.
 * @example
 * ```html
 * <igx-grid [data]="employeeData" [autoGenerate]="false">
 *   <igx-column field="first" header="First Name"></igx-column>
 *   <igx-column field="last" header="Last Name"></igx-column>
 *   <igx-column field="role" header="Role"></igx-column>
 * </igx-grid>
 * ```
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    preserveWhitespaces: false,
    providers: [
        IgxGridCRUDService,
        IgxGridNavigationService,
        IgxGridSummaryService,
        IgxGridSelectionService,
        IgxGridValidationService,
        { provide: IGX_GRID_SERVICE_BASE, useClass: IgxGridAPIService },
        { provide: IGX_GRID_BASE, useExisting: IgxGridElementsComponent },
        IgxFilteringService,
        IgxColumnResizingService,
        IgxForOfSyncService,
        IgxForOfScrollSyncService,
    ],
    imports: [
           NgClass,
           NgStyle,
           NgTemplateOutlet,
           IgxGridGroupByAreaComponent,
           IgxGridHeaderRowComponent,
           IgxGridBodyDirective,
           IgxGridDragSelectDirective,
           IgxColumnMovingDropDirective,
           IgxGridForOfDirective,
           IgxTemplateOutletDirective,
           IgxGridRowComponent,
           IgxGridGroupByRowComponent,
           IgxSummaryRowComponent,
           IgxOverlayOutletDirective,
           IgxToggleDirective,
           IgxCircularProgressBarComponent,
           IgxSnackbarComponent,
           IgxButtonDirective,
           IgxRippleDirective,
           IgxIconComponent,
           IgxRowEditTabStopDirective,
           IgxGridColumnResizerComponent,
           IgxGridTransactionPipe,
           IgxHasVisibleColumnsPipe,
           IgxGridRowPinningPipe,
           IgxGridAddRowPipe,
           IgxGridRowClassesPipe,
           IgxGridRowStylesPipe,
           IgxSummaryDataPipe,
           IgxGridGroupingPipe,
           IgxGridPagingPipe,
           IgxGridSortingPipe,
           IgxGridFilteringPipe,
           IgxGridSummaryPipe,
           IgxGridDetailsPipe,
           IgxStringReplacePipe,
           IgxGridCellMergePipe,
           IgxGridUnmergeActivePipe,
           IgxScrollInertiaDirective
       ],
    selector: 'igx-grid',
    templateUrl: '../../../../igniteui-angular/grids/grid/src/grid.component.html',
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IgxGridElementsComponent extends IgxGridComponent {

    @Output()
    public columnsAutogenerated = new EventEmitter<IColumnsAutoGeneratedEventArgs>();

    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ActionStripCollection */
    /* blazorCollectionItemName: ActionStrip */
    /* ngQueryListName: actionStripComponents */
    @ContentChildren(IgxActionStripToken)
    public actionStripComponents: QueryList<IgxActionStripToken>;

    protected override autogenerateColumns() {
        super.autogenerateColumns();
        this.columnsAutogenerated.emit({ columns: this._autoGeneratedCols });
    }
}
