import { ChangeDetectionStrategy, ChangeDetectorRef, Component, ContentChildren, CUSTOM_ELEMENTS_SCHEMA, ElementRef, EnvironmentInjector, EventEmitter, Inject, Injector, IterableDiffers, LOCALE_ID, NgZone, Optional, Output, QueryList, ViewContainerRef } from '@angular/core';
import { IgxGridComponent } from '../../../../igniteui-angular/src/lib/grids/grid/grid.component';
import { IColumnsAutoGeneratedEventArgs } from './events';
import { IgxGridCRUDService } from '../../../../igniteui-angular/src/lib/grids/common/crud.service';
import { IgxGridNavigationService } from '../../../../igniteui-angular/src/lib/grids/grid-navigation.service';
import { IgxGridSummaryService } from '../../../../igniteui-angular/src/lib/grids/summaries/grid-summary.service';
import { IgxGridSelectionService } from '../../../../igniteui-angular/src/lib/grids/selection/selection.service';
import { IgxGridValidationService } from '../../../../igniteui-angular/src/lib/grids/grid/grid-validation.service';
import { GridServiceType, IGX_GRID_BASE, IGX_GRID_SERVICE_BASE, IgxButtonDirective, IgxCircularProgressBarComponent, IgxColumnComponent, IgxFlatTransactionFactory, IgxGridForOfDirective, IgxGridHeaderRowComponent, IgxGridToolbarComponent, IgxGridTransaction, IgxIconComponent, IgxOverlayOutletDirective, IgxOverlayService, IgxPaginatorComponent, IgxRippleDirective, IgxRowEditTabStopDirective, IgxSnackbarComponent, IgxTemplateOutletDirective, IgxTextHighlightService, IgxToggleDirective, State, Transaction, TransactionService } from 'igniteui-angular';
import { IgxGridAPIService } from '../../../../igniteui-angular/src/lib/grids/grid/grid-api.service';
import { IgxFilteringService } from '../../../../igniteui-angular/src/lib/grids/filtering/grid-filtering.service';
import { IgxColumnResizingService } from '../../../../igniteui-angular/src/lib/grids/resizing/resizing.service';
import { IgxForOfScrollSyncService, IgxForOfSyncService } from '../../../../igniteui-angular/src/lib/directives/for-of/for_of.sync.service';
import { IgxActionStripToken } from '../../../../igniteui-angular/src/lib/action-strip/token';
import { takeUntil } from 'rxjs';
import { DOCUMENT, NgClass, NgFor, NgIf, NgStyle, NgTemplateOutlet } from '@angular/common';
import { PlatformUtil } from '../../../../igniteui-angular/src/lib/core/utils';
import { IgxGridGroupByAreaComponent } from '../../../../igniteui-angular/src/lib/grids/grouping/grid-group-by-area.component';
import { IgxGridBodyDirective } from '../../../../igniteui-angular/src/lib/grids/grid.common';
import { IgxGridDragSelectDirective } from '../../../../igniteui-angular/src/lib/grids/selection/drag-select.directive';
import { IgxColumnMovingDropDirective } from '../../../../igniteui-angular/src/lib/grids/moving/moving.drop.directive';
import { IgxGridRowComponent } from '../../../../igniteui-angular/src/lib/grids/grid/grid-row.component';
import { IgxGridGroupByRowComponent } from '../../../../igniteui-angular/src/lib/grids/grid/groupby-row.component';
import { IgxSummaryRowComponent } from '../../../../igniteui-angular/src/lib/grids/summaries/summary-row.component';
import { IgxGridColumnResizerComponent } from '../../../../igniteui-angular/src/lib/grids/resizing/resizer.component';
import { IgxGridAddRowPipe, IgxGridRowClassesPipe, IgxGridRowPinningPipe, IgxGridRowStylesPipe, IgxGridTransactionPipe, IgxHasVisibleColumnsPipe, IgxStringReplacePipe } from '../../../../igniteui-angular/src/lib/grids/common/pipes';
import { IgxSummaryDataPipe } from '../../../../igniteui-angular/src/lib/grids/summaries/grid-root-summary.pipe';
import { IgxGridFilteringPipe, IgxGridGroupingPipe, IgxGridPagingPipe, IgxGridSortingPipe } from '../../../../igniteui-angular/src/lib/grids/grid/grid.pipes';
import { IgxGridSummaryPipe } from '../../../../igniteui-angular/src/lib/grids/grid/grid.summary.pipe';
import { IgxGridDetailsPipe } from '../../../../igniteui-angular/src/lib/grids/grid/grid.details.pipe';

/* blazorAdditionalDependency: Column */
/* blazorAdditionalDependency: ColumnGroup */
/* blazorAdditionalDependency: ColumnLayout */
/* blazorAdditionalDependency: GridToolbar */
/* blazorAdditionalDependency: GridToolbarActions */
/* blazorAdditionalDependency: GridToolbarTitle */
/* blazorAdditionalDependency: GridToolbarAdvancedFiltering */
/* blazorAdditionalDependency: GridToolbarExporter */
/* blazorAdditionalDependency: GridToolbarHiding */
/* blazorAdditionalDependency: GridToolbarPinning */
/* blazorAdditionalDependency: ActionStrip */
/* blazorAdditionalDependency: GridActionsBaseDirective */
/* blazorAdditionalDependency: GridEditingActions */
/* blazorAdditionalDependency: GridPinningActions */
/* blazorIndirectRender */
/**
 * Grid provides a way to present and manipulate tabular data.
 *
 * @igxModule IgxGridModule
 * @igxGroup Grids & Lists
 * @igxKeywords grid, table
 * @igxTheme igx-grid-theme
 * @remarks
 * The Ignite UI Grid is used for presenting and manipulating tabular data in the simplest way possible.  Once data
 * has been bound, it can be manipulated through filtering, sorting & editing operations.
 * @example
 * ```html
 * <igx-grid [data]="employeeData" [autoGenerate]="false">
 *   <igx-column field="first" header="First Name"></igx-column>
 *   <igx-column field="last" header="Last Name"></igx-column>
 *   <igx-column field="role" header="Role"></igx-column>
 * </igx-grid>
 * ```
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    preserveWhitespaces: false,
    providers: [
        IgxGridCRUDService,
        IgxGridNavigationService,
        IgxGridSummaryService,
        IgxGridSelectionService,
        IgxGridValidationService,
        { provide: IGX_GRID_SERVICE_BASE, useClass: IgxGridAPIService },
        { provide: IGX_GRID_BASE, useExisting: IgxGridElementsComponent },
        IgxFilteringService,
        IgxColumnResizingService,
        IgxForOfSyncService,
        IgxForOfScrollSyncService,
    ],
    imports: [
        NgClass,
        NgStyle,
        NgTemplateOutlet,
        IgxGridGroupByAreaComponent,
        IgxGridHeaderRowComponent,
        IgxGridBodyDirective,
        IgxGridDragSelectDirective,
        IgxColumnMovingDropDirective,
        IgxGridForOfDirective,
        IgxTemplateOutletDirective,
        IgxGridRowComponent,
        IgxGridGroupByRowComponent,
        IgxSummaryRowComponent,
        IgxOverlayOutletDirective,
        IgxToggleDirective,
        IgxCircularProgressBarComponent,
        IgxSnackbarComponent,
        IgxButtonDirective,
        IgxRippleDirective,
        IgxIconComponent,
        IgxRowEditTabStopDirective,
        IgxGridColumnResizerComponent,
        IgxGridTransactionPipe,
        IgxHasVisibleColumnsPipe,
        IgxGridRowPinningPipe,
        IgxGridAddRowPipe,
        IgxGridRowClassesPipe,
        IgxGridRowStylesPipe,
        IgxSummaryDataPipe,
        IgxGridGroupingPipe,
        IgxGridPagingPipe,
        IgxGridSortingPipe,
        IgxGridFilteringPipe,
        IgxGridSummaryPipe,
        IgxGridDetailsPipe,
        IgxStringReplacePipe,
    ],
    selector: 'igx-grid',
    templateUrl: '../../../../igniteui-angular/src/lib/grids/grid/grid.component.html',
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IgxGridElementsComponent extends IgxGridComponent {

    constructor(
        public override readonly validation: IgxGridValidationService,
        /** @hidden @internal */
        public override readonly selectionService: IgxGridSelectionService,
        protected override colResizingService: IgxColumnResizingService,
        @Inject(IGX_GRID_SERVICE_BASE) public override readonly gridAPI: GridServiceType,
        protected override transactionFactory: IgxFlatTransactionFactory,
        private elementRef1: ElementRef<HTMLElement>,
        protected override zone: NgZone,
        /** @hidden @internal */
        @Inject(DOCUMENT) public override document: any,
        public override readonly cdr: ChangeDetectorRef,
        protected override differs: IterableDiffers,
        protected override viewRef: ViewContainerRef,
        protected override injector: Injector,
        protected override envInjector: EnvironmentInjector,
        public override navigation: IgxGridNavigationService,
        /** @hidden @internal */
        public override filteringService: IgxFilteringService,
        protected override textHighlightService: IgxTextHighlightService,
        @Inject(IgxOverlayService) protected override overlayService: IgxOverlayService,
        /** @hidden @internal */
        public override summaryService: IgxGridSummaryService,
        @Inject(LOCALE_ID) private localeId1: string,
        protected override platform: PlatformUtil,
        @Optional() @Inject(IgxGridTransaction) protected override _diTransactions?: TransactionService<Transaction, State>,
    ) {
        super(validation, selectionService,colResizingService, gridAPI, transactionFactory, elementRef1, zone,
            document, cdr, differs, viewRef,injector, envInjector, navigation, filteringService, textHighlightService, overlayService,
            summaryService, localeId1, platform, _diTransactions
        );
    }

    @Output()
    public columnsAutogenerated = new EventEmitter<IColumnsAutoGeneratedEventArgs>();

    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ActionStripCollection */
    /* blazorCollectionItemName: ActionStrip */
    /* ngQueryListName: actionStripComponents */
    @ContentChildren(IgxActionStripToken)
    public actionStripComponents: QueryList<IgxActionStripToken>;

    protected override autogenerateColumns() {
        super.autogenerateColumns();
        this.columnsAutogenerated.emit({ columns: this._autoGeneratedCols });
    }
}
