
import { ChangeDetectionStrategy, Component, ContentChildren, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Output, QueryList, reflectComponentType, ViewChildren } from '@angular/core';
import { NgClass, NgTemplateOutlet, NgStyle } from '@angular/common';

import { IgxHierarchicalGridAPIService } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid-api.service';
import { IgxFilteringService, IgxGridNavigationService, IgxGridValidationService } from 'igniteui-angular/grids/core';
import { IgxHierarchicalGridNavigationService } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid-navigation.service';
import { IgxGridSummaryService } from 'igniteui-angular/grids/core';
import { takeUntil } from 'rxjs/operators';
import { IGX_GRID_BASE, IGX_GRID_SERVICE_BASE } from 'igniteui-angular/grids/core';
import { IgxRowIslandAPIService } from 'igniteui-angular/grids/hierarchical-grid/src/row-island-api.service';
import { IgxGridCRUDService } from 'igniteui-angular/grids/core';
import { IgxColumnResizingService } from 'igniteui-angular/grids/core';
import { IgxGridHierarchicalPipe, IgxGridHierarchicalPagingPipe } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid.pipes';
import { IgxSummaryDataPipe } from 'igniteui-angular/grids/core';
import { IgxGridTransactionPipe, IgxHasVisibleColumnsPipe, IgxGridRowPinningPipe, IgxGridAddRowPipe, IgxGridRowClassesPipe, IgxGridRowStylesPipe, IgxStringReplacePipe } from 'igniteui-angular/grids/core';
import { IgxGridColumnResizerComponent } from 'igniteui-angular/grids/core';
import { IgxRowEditTabStopDirective } from 'igniteui-angular/grids/core';
import { IgxSummaryRowComponent } from 'igniteui-angular/grids/core';
import { IgxHierarchicalRowComponent } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-row.component';
import { IgxColumnMovingDropDirective } from 'igniteui-angular/grids/core';
import { IgxGridDragSelectDirective } from 'igniteui-angular/grids/core';
import { IgxGridBodyDirective } from 'igniteui-angular/grids/core';
import { IgxGridHeaderRowComponent } from 'igniteui-angular/grids/core';
import { IgxGridSelectionService } from 'igniteui-angular/grids/core';
import { IgxButtonDirective, IgxForOfScrollSyncService, IgxForOfSyncService, IgxGridForOfDirective, IgxRippleDirective, IgxScrollInertiaDirective, IgxTemplateOutletDirective, IgxToggleDirective } from 'igniteui-angular/directives';
import { IgxCircularProgressBarComponent } from 'igniteui-angular/progressbar';
import { IgxSnackbarComponent } from 'igniteui-angular/snackbar';
import { IgxIconComponent } from 'igniteui-angular/icon';
import { IgxActionStripToken, IgxOverlayOutletDirective } from 'igniteui-angular/core';
import { IgxGridCellMergePipe, IgxGridFilteringPipe, IgxGridSortingPipe, IgxGridUnmergeActivePipe } from 'igniteui-angular/grids/grid';
import { IgxChildGridRowComponent as IgxChildGridRow, IgxHierarchicalGridComponent as IgxHierarchicalGrid } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid.component';
import { IgxRowIslandComponent } from './row-island.component';
import { IColumnsAutoGeneratedEventArgs } from './events';


/**
 * @hidden @internal
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'igx-child-grid-row',
    templateUrl: '../../../../igniteui-angular/grids/hierarchical-grid/src/child-grid-row.component.html',
    imports: [NgClass]
})
export class IgxChildGridRowComponent extends IgxChildGridRow {

    /**
     * @hidden
     */
    public override hGrid: IgxHierarchicalGridComponent;

    /**
     * @hidden
     */
    public override ngOnInit() {
        const ref = this.container.createComponent(IgxHierarchicalGridComponent, { injector: this.container.injector });
        this.hGrid = ref.instance;
        this.hGrid.setDataInternal(this.data.childGridsData[this.layout.key]);
        this.hGrid.nativeElement["__componentRef"] = ref;
        this.layout.layoutChange.subscribe((ch) => {
            this._handleLayoutChanges(ch);
        });
        const changes = this.layout.initialChanges;
        changes.forEach(change => {
            this._handleLayoutChanges(change);
        });
        this.hGrid.parent = this.parentGrid;
        this.hGrid.parentIsland = this.layout;
        this.hGrid.childRow = this;
        // handler logic that re-emits hgrid events on the row island
        this.setupEventEmitters();
        this.layout.gridCreated.emit({
            owner: this.layout,
            parentID: this.data.rowID,
            grid: this.hGrid,
            parentRowData: this.data.parentRowData,
        });
    }

    protected override setupEventEmitters() {
        const destructor = takeUntil(this.hGrid.destroy$);
        // use wc type so that it includes elements specific events: childrenResolved, columnsAutogenerated, etc.
        const mirror = reflectComponentType(IgxHierarchicalGridComponent);
        // exclude outputs related to two-way binding functionality
        const inputNames = mirror.inputs.map(input => input.propName);
        const outputs = mirror.outputs.filter(o => {
            const matchingInputPropName = o.propName.slice(0, o.propName.indexOf('Change'));
            return inputNames.indexOf(matchingInputPropName) === -1;
        });

        // TODO: Skip the `rendered` output. Rendered should be called once per grid.
        outputs.filter(o => o.propName !== 'rendered').forEach(output => {
            if (this.hGrid[output.propName]) {
                this.hGrid[output.propName].pipe(destructor).subscribe((args) => {
                    if (!args) {
                        args = {};
                    }
                    args.owner = this.hGrid;
                    this.layout[output.propName].emit(args);
                });
            }
        });
    }

}

/* blazorAdditionalDependency: Column */
/* blazorAdditionalDependency: ColumnGroup */
/* blazorAdditionalDependency: ColumnLayout */
/* blazorAdditionalDependency: GridToolbar */
/* blazorAdditionalDependency: GridToolbarActions */
/* blazorAdditionalDependency: GridToolbarTitle */
/* blazorAdditionalDependency: GridToolbarAdvancedFiltering */
/* blazorAdditionalDependency: GridToolbarExporter */
/* blazorAdditionalDependency: GridToolbarHiding */
/* blazorAdditionalDependency: GridToolbarPinning */
/* blazorAdditionalDependency: ActionStrip */
/* blazorAdditionalDependency: GridActionsBaseDirective */
/* blazorAdditionalDependency: GridEditingActions */
/* blazorAdditionalDependency: GridPinningActions */
/* blazorAdditionalDependency: RowIsland */
/* blazorIndirectRender */
/**
 * Hierarchical grid
 *
 * @igxModule IgxHierarchicalGridModule
 *
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'igx-hierarchical-grid',
    templateUrl: '../../../../igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid.component.html',
    providers: [
        IgxGridCRUDService,
        IgxGridValidationService,
        IgxGridSelectionService,
        { provide: IGX_GRID_SERVICE_BASE, useClass: IgxHierarchicalGridAPIService },
        { provide: IGX_GRID_BASE, useExisting: IgxHierarchicalGridComponent },
        IgxGridSummaryService,
        IgxFilteringService,
        IgxGridNavigationService,
        IgxHierarchicalGridNavigationService,
        IgxColumnResizingService,
        IgxForOfSyncService,
        IgxForOfScrollSyncService,
        IgxRowIslandAPIService
    ],
    imports: [
        NgClass,
        NgTemplateOutlet,
        NgStyle,
        IgxGridHeaderRowComponent,
        IgxGridBodyDirective,
        IgxGridDragSelectDirective,
        IgxColumnMovingDropDirective,
        IgxGridForOfDirective,
        IgxTemplateOutletDirective,
        IgxHierarchicalRowComponent,
        IgxOverlayOutletDirective,
        IgxToggleDirective,
        IgxCircularProgressBarComponent,
        IgxSnackbarComponent,
        IgxSummaryRowComponent,
        IgxButtonDirective,
        IgxRippleDirective,
        IgxIconComponent,
        IgxRowEditTabStopDirective,
        IgxGridColumnResizerComponent,
        IgxChildGridRowComponent,
        IgxGridSortingPipe,
        IgxGridFilteringPipe,
        IgxGridTransactionPipe,
        IgxHasVisibleColumnsPipe,
        IgxGridRowPinningPipe,
        IgxGridAddRowPipe,
        IgxGridRowClassesPipe,
        IgxGridRowStylesPipe,
        IgxSummaryDataPipe,
        IgxGridHierarchicalPipe,
        IgxGridHierarchicalPagingPipe,
        IgxStringReplacePipe,
        IgxGridCellMergePipe,
        IgxScrollInertiaDirective,
        IgxGridUnmergeActivePipe
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IgxHierarchicalGridComponent extends IgxHierarchicalGrid {

    constructor() {
        super();
        this.selectionService.selectedRowsChange.pipe(takeUntil(this.destroy$)).subscribe((args: any[]) => {
            this.selectedRowsChange.emit(args);
        });
    }

    /**
     * @hidden
     */
    @ViewChildren(IgxChildGridRowComponent)
    public override hierarchicalRows: QueryList<IgxChildGridRowComponent>;

    /**
     * @hidden
     * @internal
     */
    /* blazorInclude */
    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: RowIslandCollection */
    /* ngQueryListName: childLayoutList */
    @ContentChildren(IgxRowIslandComponent, { read: IgxRowIslandComponent, descendants: false })
    public override childLayoutList: QueryList<IgxRowIslandComponent>;

    /**
     * @hidden
     */
    @ContentChildren(IgxRowIslandComponent, { read: IgxRowIslandComponent, descendants: true })
    public override allLayoutList: QueryList<IgxRowIslandComponent>;

    @Output()
    public columnsAutogenerated = new EventEmitter<IColumnsAutoGeneratedEventArgs>();

    /**
     * Emitted when content children are resolved and collections in grid are updated.
     */
    @Output()
    public childrenResolved = new EventEmitter<void>();

    /** @hidden @internal */
    /* blazorInclude */
    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ActionStripCollection */
    /* blazorCollectionItemName: ActionStrip */
    /* ngQueryListName: actionStripComponents */
    @ContentChildren(IgxActionStripToken)
    public actionStripComponents: QueryList<IgxActionStripToken>;

    protected override autogenerateColumns() {
        super.autogenerateColumns();
        this.columnsAutogenerated.emit({ columns: this._autoGeneratedCols });
    }
}
