
import { ChangeDetectionStrategy, Component, ContentChildren, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Output, QueryList } from '@angular/core';
import { NgClass, NgTemplateOutlet, NgStyle } from '@angular/common';

import { IgxHierarchicalGridAPIService } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid-api.service';
import { IgxFilteringService, IgxGridValidationService } from 'igniteui-angular/grids/core';
import { IgxHierarchicalGridNavigationService } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid-navigation.service';
import { IgxGridSummaryService } from 'igniteui-angular/grids/core';
import { takeUntil } from 'rxjs/operators';
import { IGX_GRID_BASE, IGX_GRID_SERVICE_BASE } from 'igniteui-angular/grids/core';
import { IgxRowIslandAPIService } from 'igniteui-angular/grids/hierarchical-grid/src/row-island-api.service';
import { IgxGridCRUDService } from 'igniteui-angular/grids/core';
import { IgxColumnResizingService } from 'igniteui-angular/grids/core';
import { IgxGridHierarchicalPipe, IgxGridHierarchicalPagingPipe } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid.pipes';
import { IgxSummaryDataPipe } from 'igniteui-angular/grids/core';
import { IgxGridTransactionPipe, IgxHasVisibleColumnsPipe, IgxGridRowPinningPipe, IgxGridAddRowPipe, IgxGridRowClassesPipe, IgxGridRowStylesPipe, IgxStringReplacePipe } from 'igniteui-angular/grids/core';
import { IgxGridColumnResizerComponent } from 'igniteui-angular/grids/core';
import { IgxRowEditTabStopDirective } from 'igniteui-angular/grids/core';
import { IgxSummaryRowComponent } from 'igniteui-angular/grids/core';
import { IgxHierarchicalRowComponent } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-row.component';
import { IgxColumnMovingDropDirective } from 'igniteui-angular/grids/core';
import { IgxGridDragSelectDirective } from 'igniteui-angular/grids/core';
import { IgxGridBodyDirective } from 'igniteui-angular/grids/core';
import { IgxGridHeaderRowComponent } from 'igniteui-angular/grids/core';
import { IgxGridSelectionService } from 'igniteui-angular/grids/core';
import { IgxButtonDirective, IgxForOfScrollSyncService, IgxForOfSyncService, IgxGridForOfDirective, IgxRippleDirective, IgxScrollInertiaDirective, IgxTemplateOutletDirective, IgxToggleDirective } from 'igniteui-angular/directives';
import { IgxCircularProgressBarComponent } from 'igniteui-angular/progressbar';
import { IgxSnackbarComponent } from 'igniteui-angular/snackbar';
import { IgxIconComponent } from 'igniteui-angular/icon';
import {IgxActionStripToken, IgxOverlayOutletDirective } from 'igniteui-angular/core';
import { IgxGridCellMergePipe, IgxGridFilteringPipe, IgxGridSortingPipe, IgxGridUnmergeActivePipe } from 'igniteui-angular/grids/grid';
import { IgxChildGridRowComponent, IgxHierarchicalGridComponent } from 'igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid.component';
import { IgxRowIslandElementsComponent } from './row-island.component';
import { IColumnsAutoGeneratedEventArgs } from './events';


/* blazorAdditionalDependency: Column */
/* blazorAdditionalDependency: ColumnGroup */
/* blazorAdditionalDependency: ColumnLayout */
/* blazorAdditionalDependency: GridToolbar */
/* blazorAdditionalDependency: GridToolbarActions */
/* blazorAdditionalDependency: GridToolbarTitle */
/* blazorAdditionalDependency: GridToolbarAdvancedFiltering */
/* blazorAdditionalDependency: GridToolbarExporter */
/* blazorAdditionalDependency: GridToolbarHiding */
/* blazorAdditionalDependency: GridToolbarPinning */
/* blazorAdditionalDependency: ActionStrip */
/* blazorAdditionalDependency: GridActionsBaseDirective */
/* blazorAdditionalDependency: GridEditingActions */
/* blazorAdditionalDependency: GridPinningActions */
/* blazorAdditionalDependency: RowIsland */
/* blazorIndirectRender */
/**
 * Hierarchical grid
 *
 * @igxModule IgxHierarchicalGridModule
 *
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'igx-hierarchical-grid',
    templateUrl: '../../../../igniteui-angular/grids/hierarchical-grid/src/hierarchical-grid.component.html',
    providers: [
        IgxGridCRUDService,
        IgxGridValidationService,
        IgxGridSelectionService,
        { provide: IGX_GRID_SERVICE_BASE, useClass: IgxHierarchicalGridAPIService },
        { provide: IGX_GRID_BASE, useExisting: IgxHierarchicalGridElementsComponent },
        IgxGridSummaryService,
        IgxFilteringService,
        IgxHierarchicalGridNavigationService,
        IgxColumnResizingService,
        IgxForOfSyncService,
        IgxForOfScrollSyncService,
        IgxRowIslandAPIService
    ],
    imports: [
        NgClass,
        NgTemplateOutlet,
        NgStyle,
        IgxGridHeaderRowComponent,
        IgxGridBodyDirective,
        IgxGridDragSelectDirective,
        IgxColumnMovingDropDirective,
        IgxGridForOfDirective,
        IgxTemplateOutletDirective,
        IgxHierarchicalRowComponent,
        IgxOverlayOutletDirective,
        IgxToggleDirective,
        IgxCircularProgressBarComponent,
        IgxSnackbarComponent,
        IgxSummaryRowComponent,
        IgxButtonDirective,
        IgxRippleDirective,
        IgxIconComponent,
        IgxRowEditTabStopDirective,
        IgxGridColumnResizerComponent,
        IgxChildGridRowComponent,
        IgxGridSortingPipe,
        IgxGridFilteringPipe,
        IgxGridTransactionPipe,
        IgxHasVisibleColumnsPipe,
        IgxGridRowPinningPipe,
        IgxGridAddRowPipe,
        IgxGridRowClassesPipe,
        IgxGridRowStylesPipe,
        IgxSummaryDataPipe,
        IgxGridHierarchicalPipe,
        IgxGridHierarchicalPagingPipe,
        IgxStringReplacePipe,
        IgxGridCellMergePipe,
        IgxScrollInertiaDirective,
        IgxGridUnmergeActivePipe
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IgxHierarchicalGridElementsComponent extends IgxHierarchicalGridComponent {

    constructor() {
        super();
        this.selectionService.selectedRowsChange.pipe(takeUntil(this.destroy$)).subscribe((args: any[]) => {
            this.selectedRowsChange.emit(args);
        });
    }

    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: RowIslandCollection */
    /* ngQueryListName: childLayoutList */
    @ContentChildren(IgxRowIslandElementsComponent, { read: IgxRowIslandElementsComponent, descendants: false })
    public override childLayoutList: QueryList<IgxRowIslandElementsComponent>;

    /**
     * @hidden
     */
    @ContentChildren(IgxRowIslandElementsComponent, { read: IgxRowIslandElementsComponent, descendants: true })
    public override allLayoutList: QueryList<IgxRowIslandElementsComponent>;

    @Output()
    public columnsAutogenerated = new EventEmitter<IColumnsAutoGeneratedEventArgs>();

    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ActionStripCollection */
    /* blazorCollectionItemName: ActionStrip */
    /* ngQueryListName: actionStripComponents */
    @ContentChildren(IgxActionStripToken)
    public actionStripComponents: QueryList<IgxActionStripToken>;

    protected override autogenerateColumns() {
        super.autogenerateColumns();
        this.columnsAutogenerated.emit({ columns: this._autoGeneratedCols });
    }
}
