/* blazorCopyInheritedMembers */
/* blazorElement */
/* wcElementTag: igc-row-island */
/* blazorIndirectRender */
/* jsonAPIManageCollectionInMarkup */
/* jsonAPIManageItemInMarkup */
/* mustUseNGParentAnchor */
/* additionalIdentifier: ChildDataKey */
/* contentParent: RowIsland */
/* contentParent: HierarchicalGrid */

import { ChangeDetectionStrategy, Component, ContentChildren, EventEmitter, forwardRef, Input, Output, QueryList } from '@angular/core';
import { IgxRowIslandComponent } from 'igniteui-angular/grids/hierarchical-grid/src/row-island.component';
import { IgxFilteringService } from 'igniteui-angular/grids/core';
import { IgxRowIslandAPIService } from 'igniteui-angular/grids/hierarchical-grid/src/row-island-api.service';
import { IgxGridSelectionService } from 'igniteui-angular/grids/core';
import { IColumnsAutoGeneratedEventArgs } from './events';
import { IgxActionStripToken } from 'igniteui-angular/core';

/**
 * Row island
 *
 * @igxModule IgxHierarchicalGridModule
 * @igxParent IgxGridElementsComponent, IgxHierarchicalGridElementsComponent, IgxRowIslandElementsComponent
 *
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'igx-row-island',
    template: `<div #sink style="display: none;">
    <ng-content select="igx-column,igc-column,igx-column-group,igc-column-group,igx-action-strip,igc-action-strip"></ng-content>
    <ng-content select="igx-row-island,igc-row-island"></ng-content>
    </div>`,
    providers: [
        IgxRowIslandAPIService,
        IgxFilteringService,
        IgxGridSelectionService
    ],
    standalone: true
})
export class IgxRowIslandElementsComponent extends IgxRowIslandComponent {

    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: RowIslandCollection */
    /* ngQueryListName: childLayoutList */
    @ContentChildren(IgxRowIslandElementsComponent, { read: IgxRowIslandElementsComponent, descendants: false })
    public override childLayoutList: QueryList<IgxRowIslandElementsComponent>;

    /**
     * @hidden
     */
    @ContentChildren(forwardRef(() => IgxRowIslandElementsComponent), { read: IgxRowIslandElementsComponent, descendants: false })
    public override children = new QueryList<IgxRowIslandElementsComponent>();

    @Output()
    public columnsAutogenerated = new EventEmitter<IColumnsAutoGeneratedEventArgs>();

    // TODO(api-analyzer): Shouldn't need all tags to copy from base or hidden/internal due to include tag
    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ActionStripCollection */
    /* blazorCollectionItemName: ActionStrip */
    /* ngQueryListName: actionStripComponents */
    @ContentChildren(IgxActionStripToken, { read: IgxActionStripToken, descendants: false })
    protected actionStripComponents: QueryList<IgxActionStripToken>;

    protected override autogenerateColumns() {
        super.autogenerateColumns();
        this.columnsAutogenerated.emit({ columns: this._autoGeneratedCols });
    }

    /**
     * Sets the key of the row island by which child data would be taken from the row data if such is provided.
     */
    @Input()
    public get childDataKey() {
        return this.key;
    }

    public set childDataKey(value: string) {
        this.key = value;
    }
}
