import { NgClass, NgStyle, NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, ContentChildren, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Output, QueryList } from '@angular/core';
import { IgxTreeGridAPIService } from 'igniteui-angular/grids/tree-grid/src/tree-grid-api.service';
import { IgxGridCellMergePipe, IgxGridUnmergeActivePipe } from 'igniteui-angular/grids/grid';
import {
    IGX_GRID_BASE,
    IGX_GRID_SERVICE_BASE,
    IgxColumnMovingDropDirective,
    IgxColumnResizingService,
    IgxFilteringService,
    IgxGridBodyDirective,
    IgxGridColumnResizerComponent,
    IgxGridCRUDService,
    IgxGridDragSelectDirective,
    IgxGridHeaderRowComponent,
    IgxGridNavigationService,
    IgxGridRowClassesPipe,
    IgxGridRowPinningPipe,
    IgxGridRowStylesPipe,
    IgxGridSelectionService,
    IgxGridSummaryService,
    IgxGridValidationService,
    IgxHasVisibleColumnsPipe,
    IgxRowEditTabStopDirective,
    IgxStringReplacePipe,
    IgxSummaryDataPipe,
    IgxSummaryRowComponent,
} from 'igniteui-angular/grids/core';
import { IgxTreeGridSelectionService } from 'igniteui-angular/grids/tree-grid/src/tree-grid-selection.service';
import { IgxActionStripToken, IgxOverlayOutletDirective } from 'igniteui-angular/core';
import { IgxTreeGridSummaryPipe } from 'igniteui-angular/grids/tree-grid/src/tree-grid.summary.pipe';
import { IgxTreeGridFilteringPipe } from 'igniteui-angular/grids/tree-grid/src/tree-grid.filtering.pipe';
import { IgxTreeGridHierarchizingPipe, IgxTreeGridFlatteningPipe, IgxTreeGridSortingPipe, IgxTreeGridPagingPipe, IgxTreeGridTransactionPipe, IgxTreeGridNormalizeRecordsPipe, IgxTreeGridAddRowPipe } from 'igniteui-angular/grids/tree-grid/src/tree-grid.pipes';
import { IgxTreeGridRowComponent } from 'igniteui-angular/grids/tree-grid/src/tree-grid-row.component';
import { IgxButtonDirective, IgxForOfScrollSyncService, IgxForOfSyncService, IgxGridForOfDirective, IgxRippleDirective, IgxScrollInertiaDirective, IgxTemplateOutletDirective, IgxToggleDirective } from 'igniteui-angular/directives';
import { IgxCircularProgressBarComponent } from 'igniteui-angular/progressbar';
import { IgxSnackbarComponent } from 'igniteui-angular/snackbar';
import { IgxIconComponent } from 'igniteui-angular/icon';
import { IgxTreeGridComponent } from 'igniteui-angular/grids/tree-grid/src/tree-grid.component';
import { IColumnsAutoGeneratedEventArgs } from './events';


/* blazorAdditionalDependency: Column */
/* blazorAdditionalDependency: ColumnGroup */
/* blazorAdditionalDependency: ColumnLayout */
/* blazorAdditionalDependency: GridToolbar */
/* blazorAdditionalDependency: GridToolbarActions */
/* blazorAdditionalDependency: GridToolbarTitle */
/* blazorAdditionalDependency: GridToolbarAdvancedFiltering */
/* blazorAdditionalDependency: GridToolbarExporter */
/* blazorAdditionalDependency: GridToolbarHiding */
/* blazorAdditionalDependency: GridToolbarPinning */
/* blazorAdditionalDependency: ActionStrip */
/* blazorAdditionalDependency: GridActionsBaseDirective */
/* blazorAdditionalDependency: GridEditingActions */
/* blazorAdditionalDependency: GridPinningActions */
/* blazorIndirectRender */
/**
 * **Ignite UI for Angular Tree Grid** -
 * [Documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid)
 *
 * The Ignite UI Tree Grid displays and manipulates hierarchical data with consistent schema formatted as a table and
 * provides features such as sorting, filtering, editing, column pinning, paging, column moving and hiding.
 *
 * Example:
 * ```html
 * <igx-tree-grid [data]="employeeData" primaryKey="employeeID" foreignKey="PID" [autoGenerate]="false">
 *   <igx-column field="first" header="First Name"></igx-column>
 *   <igx-column field="last" header="Last Name"></igx-column>
 *   <igx-column field="role" header="Role"></igx-column>
 * </igx-tree-grid>
 * ```
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'igx-tree-grid',
    templateUrl: '../../../../igniteui-angular/grids/tree-grid/src/tree-grid.component.html',
    providers: [
        IgxGridCRUDService,
        IgxGridValidationService,
        IgxGridSummaryService,
        IgxGridNavigationService,
        { provide: IgxGridSelectionService, useClass: IgxTreeGridSelectionService },
        { provide: IGX_GRID_SERVICE_BASE, useClass: IgxTreeGridAPIService },
        { provide: IGX_GRID_BASE, useExisting: IgxTreeGridElementsComponent },
        IgxFilteringService,
        IgxColumnResizingService,
        IgxForOfSyncService,
        IgxForOfScrollSyncService
    ],
    imports: [
        NgClass,
        NgStyle,
        NgTemplateOutlet,
        IgxGridHeaderRowComponent,
        IgxGridBodyDirective,
        IgxGridDragSelectDirective,
        IgxColumnMovingDropDirective,
        IgxGridForOfDirective,
        IgxTemplateOutletDirective,
        IgxTreeGridRowComponent,
        IgxSummaryRowComponent,
        IgxOverlayOutletDirective,
        IgxToggleDirective,
        IgxCircularProgressBarComponent,
        IgxSnackbarComponent,
        IgxButtonDirective,
        IgxRippleDirective,
        IgxRowEditTabStopDirective,
        IgxIconComponent,
        IgxGridColumnResizerComponent,
        IgxHasVisibleColumnsPipe,
        IgxGridRowPinningPipe,
        IgxGridRowClassesPipe,
        IgxGridRowStylesPipe,
        IgxSummaryDataPipe,
        IgxTreeGridHierarchizingPipe,
        IgxTreeGridFlatteningPipe,
        IgxTreeGridSortingPipe,
        IgxTreeGridFilteringPipe,
        IgxTreeGridPagingPipe,
        IgxTreeGridTransactionPipe,
        IgxTreeGridSummaryPipe,
        IgxTreeGridNormalizeRecordsPipe,
        IgxTreeGridAddRowPipe,
        IgxStringReplacePipe,
        IgxGridCellMergePipe,
        IgxScrollInertiaDirective,
        IgxGridUnmergeActivePipe
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class IgxTreeGridElementsComponent extends IgxTreeGridComponent {
    @Output()
    public columnsAutogenerated = new EventEmitter<IColumnsAutoGeneratedEventArgs>();

    /* contentChildren */
    /* blazorTreatAsCollection */
    /* blazorCollectionName: ActionStripCollection */
    /* blazorCollectionItemName: ActionStrip */
    /* ngQueryListName: actionStripComponents */
    @ContentChildren(IgxActionStripToken)
    public actionStripComponents: QueryList<IgxActionStripToken>;

    protected override autogenerateColumns() {
        super.autogenerateColumns();
        this.columnsAutogenerated.emit({ columns: this._autoGeneratedCols });
    }
}
