#!/usr/bin/env node
'use strict';

// var message = "34wgfv34e";
// const ERROR_CODE = 1;
// var regex = /\[ref: (\d+)\]/i;

// const exec = require('child_process').exec;
// const fs = require('fs');

// if(/COMMIT_EDITMSG/g.test(process.argv[2])){
//     var contents = fs.readFileSync(process.argv[2]);
//     var res = contents.toString();
//     console.log(res);
// }

// if (!message.match(regex)) {
//     //console.log("[Policy] Your message is not formatted correctly");
//     process.exitCode = ERROR_CODE;
// }