#!/usr/bin/env node
'use strict';

var validate = require('./scripts/validate'),
    fs = require('fs');

var options = {
    style: "default"
};

var text = fs.readFileSync(process.argv[2]).toString();

var errors = [];
errors = validate(text, options, errors);

if (errors.length > 0) {
    process.stdout.write(errors[0].toString());
    process.exitCode = 1;
}
