import { Component, OnInit, ViewChild } from '@angular/core';
import { IgxGridComponent, ISortingExpression, ISortingOptions } from 'igniteui-angular';

@Component({
    selector: 'app-grid-sorting-sample',
    templateUrl: './grid-sorting-sample.component.html',
    styleUrls: ['./grid-sorting-sample.component.scss']
})
export class GridSortingComponent implements OnInit {
    @ViewChild('grid1', { read: IgxGridComponent, static: true })
    public grid1!: IgxGridComponent;
    public data;
    public expr: ISortingExpression[];
    public selectionMode = 'multiple';
    public sortingOptions: ISortingOptions = {mode: 'multiple'};

    constructor() { }

    // eslint-disable-next-line @typescript-eslint/explicit-member-accessibility
    ngOnInit(): void {
        this.data = [
            { ShipAddress: 'Obere Str. 57', ShipCity: 'Berlin', ShipCountry: 'Germany', ShipName: "Alfred's Futterkiste", ShipRegion: null, ShipPostalCode: '12209', CustomerID: 'ALFKI', CustomerName: 'Alfreds Futterkiste', Address: 'Obere Str. 57', City: 'Berlin', Region: null, PostalCode: '12209', Country: 'Germany', Salesperson: 'Margaret Peacock', OrderID: 10692, OrderDate: new Date('11/23/2016'),  ShipperName: 'United Package', ProductID: 63, ProductName: 'Vegie-spread', UnitPrice: 43.9,Quantity: 20, Discontinued: false, ExtendedPrice: 878.0, Freight: 61.02 },
            { ShipName: "Alfred's Futterkiste", ShipCity: 'Berlin', ShipRegion: null, ShipPostalCode: '12209', ShipCountry: 'Germany', CustomerID: 'ALFKI', CustomerName: 'Alfreds Futterkiste', Address: 'Obere Str. 57', City: 'Berlin', Region: null, PostalCode: '12209', Country: 'Germany', Salesperson: 'Margaret Peacock', OrderID: 10702, OrderDate: new Date('11/23/2016'), ShipperName: 'Speedy Express', ProductID: 3, ProductName: 'Aniseed Syrup', UnitPrice: 10.0, Quantity: 6, Discontinued: false, ExtendedPrice: 60.0, Freight: 23.94 },
            { ShipName: "Alfred's Futterkiste", ShipAddress: 'Obere Str. 57', ShipCity: 'Berlin', ShipRegion: null, ShipPostalCode: '12209', ShipCountry: 'Germany', CustomerID: 'ALFKI', CustomerName: 'Alfreds Futterkiste', Address: 'Obere Str. 57', City: 'Berlin', Region: null, PostalCode: '12209', Country: 'Germany', Salesperson: 'Margaret Peacock', OrderID: 10702, OrderDate: new Date('11/23/2016'), ShipperName: 'Speedy Express', ProductID: 76, ProductName: 'Lakkalik\u00f6\u00f6ri', UnitPrice: 18.0, Quantity: 15, Discontinued: false, ExtendedPrice: 270.0, Freight: 23.94 },
            { ShipName: "Alfred's Futterkiste", ShipAddress: 'Obere Str. 57', ShipCity: 'Berlin', ShipRegion: null, ShipPostalCode: '12209', ShipCountry: 'Germany', CustomerID: 'ALFKI', CustomerName: 'Alfreds Futterkiste', Address: 'Obere Str. 57', City: 'Berlin', Region: null, PostalCode: '12209', Country: 'Germany', Salesperson: 'Nancy Davolio', OrderID: 10835, OrderDate: new Date('11/23/2016'), ShipperName: 'Federal Shipping', ProductID: 59, ProductName: 'Raclette Courdavault', UnitPrice: 55.0, Quantity: 15, Discontinued: false, ExtendedPrice: 825.0, Freight: 69.53 },
            { ShipName: 'Ana Trujillo Emparedados y helados', ShipAddress: 'Avda. de la Constituci\u00f3n 2222', ShipCity: 'M\u00e9xico D.F.', ShipRegion: null, ShipPostalCode: '05021', ShipCountry: 'Mexico', CustomerID: 'ANATR', CustomerName: 'Ana Trujillo Emparedados y helados', Address: 'Avda. de la Constituci\u00f3n 2222', City: 'M\u00e9xico D.F.', Region: null, PostalCode: '05021', Country: 'Mexico', Salesperson: 'Robert King', OrderID: 10308, OrderDate: new Date('11/23/2016'), ShipperName: 'Federal Shipping', ProductID: 69, ProductName: 'Gudbrandsdalsost', UnitPrice: 28.8, Quantity: 1, Discontinued: false, ExtendedPrice: 28.8, Freight: 1.61 },
            { ShipName: 'Ana Trujillo Emparedados y helados', ShipAddress: 'Avda. de la Constituci\u00f3n 2222', ShipCity: 'M\u00e9xico D.F.', ShipRegion: null, ShipPostalCode: '05021', ShipCountry: 'Mexico', CustomerID: 'ANATR', CustomerName: 'Ana Trujillo Emparedados y helados', Address: 'Avda. de la Constituci\u00f3n 2222', City: 'M\u00e9xico D.F.', Region: null, PostalCode: '05021', Country: 'Mexico', Salesperson: 'Margaret Peacock', OrderID: 10926, OrderDate: new Date('11/23/2016'), ShipperName: 'Federal Shipping', ProductID: 72, ProductName: 'Mozzarella di Giovanni', UnitPrice: 34.8, Quantity: 10, Discontinued: false, ExtendedPrice: 348.0, Freight: 39.92 },
            { ShipName: 'Antonio Moreno Taquer\u00eda', ShipAddress: 'Mataderos 2312', ShipCity: 'M\u00e9xico D.F.', ShipRegion: null, ShipPostalCode: '05023', ShipCountry: 'Mexico', CustomerID: 'ANTON', CustomerName: 'Antonio Moreno Taquer\u00eda', Address: 'Mataderos 2312', City: 'M\u00e9xico D.F.', Region: null, PostalCode: '05023', Country: 'Mexico', Salesperson: 'Janet Leverling', OrderID: 10365, OrderDate: new Date('11/23/2016'), ShipperName: 'United Package', ProductID: 11, ProductName: 'Queso Cabrales', UnitPrice: 16.8, Quantity: 24, Discontinued: false, ExtendedPrice: 403.2, Freight: 22.0 },
            { ShipName: 'Antonio Moreno Taquer\u00eda', ShipAddress: 'Mataderos 2312', ShipCity: 'M\u00e9xico D.F.', ShipRegion: null, ShipPostalCode: '05023', ShipCountry: 'Mexico', CustomerID: 'ANTON', CustomerName: 'Antonio Moreno Taquer\u00eda', Address: 'Mataderos 2312', City: 'M\u00e9xico D.F.', Region: null, PostalCode: '05023', Country: 'Mexico', Salesperson: 'Robert King', OrderID: 10573, OrderDate: new Date('11/23/2016'), ShipperName: 'Federal Shipping', ProductID: 17, ProductName: 'Alice Mutton', UnitPrice: 39.0, Quantity: 18, Discontinued: false, ExtendedPrice: 702.0, Freight: 84.84, },
            { ShipName: 'Antonio Moreno Taquer\u00eda', ShipAddress: 'Mataderos 2312', ShipCity: 'M\u00e9xico D.F.', ShipRegion: null, ShipPostalCode: '05023', ShipCountry: 'Mexico', CustomerID: 'ANTON', CustomerName: 'Antonio Moreno Taquer\u00eda', Address: 'Mataderos 2312', City: 'M\u00e9xico D.F.', Region: null, PostalCode: '05023', Country: 'Mexico', Salesperson: 'Robert King', OrderID: 10573, OrderDate: new Date('11/23/2016'), ShipperName: 'Federal Shipping', ProductID: 34, ProductName: 'Sasquatch Ale', UnitPrice: 14.0, Quantity: 40, Discontinued: false, ExtendedPrice: 560.0, Freight: 84.84 },
            { ShipName: 'Antonio Moreno Taquer\u00eda', ShipAddress: 'Mataderos 2312', ShipCity: 'M\u00e9xico D.F.', ShipRegion: null, ShipPostalCode: '05023', ShipCountry: 'Mexico', CustomerID: 'ANTON', CustomerName: 'Antonio Moreno Taquer\u00eda', Address: 'Mataderos 2312', City: 'M\u00e9xico D.F.', Region: null, PostalCode: '05023', Country: 'Mexico', Salesperson: 'Robert King', OrderID: 10573, OrderDate: new Date('11/23/2016'), ShipperName: 'Federal Shipping', ProductID: 53, ProductName: 'Perth Pasties', UnitPrice: 32.8, Quantity: 25, Discontinued: false, ExtendedPrice: 820.0, Freight: 84.84 },
            { ShipName: 'Antonio Moreno Taquer\u00eda', ShipAddress: 'Mataderos 2312', ShipCity: 'M\u00e9xico D.F.', ShipRegion: null, ShipPostalCode: '05023', ShipCountry: 'Mexico', CustomerID: 'ANTON', CustomerName: 'Antonio Moreno Taquer\u00eda', Address: 'Mataderos 2312', City: 'M\u00e9xico D.F.', Region: null, PostalCode: '05023', Country: 'Mexico', Salesperson: 'Janet Leverling', OrderID: 10682, OrderDate: new Date('11/23/2016'), ShipperName: 'United Package', ProductID: 33, ProductName: 'Geitost', UnitPrice: 2.5, Quantity: 30, Discontinued: false, ExtendedPrice: 75.0, Freight: 36.13 },
            { ShipName: 'Die Wandernde Kuh', ShipAddress: 'Adenauerallee 900', ShipCity: 'Stuttgart', ShipRegion: null, ShipPostalCode: '70563', ShipCountry: 'Germany', CustomerID: 'WANDK', CustomerName: 'Die Wandernde Kuh', Address: 'Adenauerallee 900', City: 'Stuttgart', Region: null, PostalCode: '70563', Country: 'Germany', Salesperson: 'Andrew Fuller', OrderID: 10312, OrderDate: new Date('4/14/2016'), ShipperName: 'United Package', ProductID: 53, ProductName: 'Perth Pasties', UnitPrice: 26.2, Quantity: 20, Discontinued: false, ExtendedPrice: 524.0, Freight: 40.26 },
            { ShipName: 'Die Wandernde Kuh', ShipAddress: 'Adenauerallee 900', ShipCity: 'Stuttgart', ShipRegion: null, ShipPostalCode: '70563', ShipCountry: 'Germany', CustomerID: 'WANDK', CustomerName: 'Die Wandernde Kuh', Address: 'Adenauerallee 900', City: 'Stuttgart', Region: null, PostalCode: '70563', Country: 'Germany', Salesperson: 'Andrew Fuller', OrderID: 10312, OrderDate: new Date('4/14/2016'), ShipperName: 'United Package', ProductID: 75, ProductName: 'Rh\u00f6nbr\u00e4u Klosterbier', UnitPrice: 6.2, Quantity: 10, Discontinued: false, ExtendedPrice: 62.0, Freight: 40.26 },
            { ShipName: 'Du monde entier', ShipAddress: '67, rue des Cinquante Otages', ShipCity: 'Nantes', ShipRegion: null, ShipPostalCode: '44000', ShipCountry: 'France', CustomerID: 'DUMON', CustomerName: 'Du monde entier', Address: '67, rue des Cinquante Otages', City: 'Nantes', Region: null, PostalCode: '44000', Country: 'France', Salesperson: 'Robert King', OrderID: 10609, OrderDate: new Date('4/14/2016'), ShipperName: 'United Package', ProductID: 21, ProductName: "Sir Rodney's Scones", UnitPrice: 10.0, Quantity: 6, Discontinued: false, ExtendedPrice: 60.0, Freight: 1.85 },
            { ShipName: 'Du monde entier', ShipAddress: '67, rue des Cinquante Otages', ShipCity: 'Nantes', ShipRegion: null, ShipPostalCode: '44000', ShipCountry: 'France', CustomerID: 'DUMON', CustomerName: 'Du monde entier', Address: '67, rue des Cinquante Otages', City: 'Nantes', Region: null, PostalCode: '44000', Country: 'France', Salesperson: 'Andrew Fuller', OrderID: 10683, OrderDate: new Date('4/14/2017'), ShipperName: 'Speedy Express', ProductID: 52, ProductName: 'Filo Mix', UnitPrice: 7.0, Quantity: 9, Discontinued: false, ExtendedPrice: 63.0, Freight: 4.4 },
            { ShipName: 'Du monde entier', ShipAddress: '67, rue des Cinquante Otages', ShipCity: 'Nantes', ShipRegion: null, ShipPostalCode: '44000', ShipCountry: 'France', CustomerID: 'DUMON', CustomerName: 'Du monde entier', Address: '67, rue des Cinquante Otages', City: 'Nantes', Region: null, PostalCode: '44000', Country: 'France', Salesperson: 'Robert King', OrderID: 10890, OrderDate: new Date('4/14/2016'), ShipperName: 'Speedy Express', ProductID: 17, ProductName: 'Alice Mutton', UnitPrice: 39.0, Quantity: 15, Discontinued: false, ExtendedPrice: 585.0, Freight: 32.76 },
            { ShipName: 'Eastern Connection', ShipAddress: '35 King George', ShipCity: 'London', ShipRegion: null, ShipPostalCode: 'WX3 6FW', ShipCountry: 'UK', CustomerID: 'EASTC', CustomerName: 'Eastern Connection', Address: '35 King George', City: 'London', Region: null, PostalCode: 'WX3 6FW', Country: 'UK', Salesperson: 'Laura Callahan', OrderID: 10987, OrderDate: new Date('3/31/2017'), ShipperName: 'Speedy Express', ProductID: 72, ProductName: 'Mozzarella di Giovanni', UnitPrice: 34.8, Quantity: 20, Discontinued: false, ExtendedPrice: 696.0, Freight: 185.48 },
            { ShipName: 'Eastern Connection', ShipAddress: '35 King George', ShipCity: 'London', ShipRegion: null, ShipPostalCode: 'WX3 6FW', ShipCountry: 'UK', CustomerID: 'EASTC', CustomerName: 'Eastern Connection', Address: '35 King George', City: 'London', Region: null, PostalCode: 'WX3 6FW', Country: 'UK', Salesperson: 'Margaret Peacock', OrderID: 11024, OrderDate: new Date('4/15/2018'), ShipperName: 'Speedy Express', ProductID: 26, ProductName: 'Gumb\u00e4r Gummib\u00e4rchen', UnitPrice: 31.23, Quantity: 12, Discontinued: false, ExtendedPrice: 374.76, Freight: 74.36 },
            { ShipName: 'Eastern Connection', ShipAddress: '35 King George', ShipCity: 'London', ShipRegion: null, ShipPostalCode: 'WX3 6FW', ShipCountry: 'UK', CustomerID: 'EASTC', CustomerName: 'Eastern Connection', Address: '35 King George', City: 'London', Region: null, PostalCode: 'WX3 6FW', Country: 'UK', Salesperson: 'Margaret Peacock', OrderID: 11024, OrderDate: new Date('5/17/2017'), ShipperName: 'Speedy Express', ProductID: 33, ProductName: 'Geitost', UnitPrice: 2.5, Quantity: 30, Discontinued: false, ExtendedPrice: 75.0, Freight: 74.36 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 10511, OrderDate: new Date('10/4/2016'), ShipperName: 'Federal Shipping', ProductID: 8, ProductName: 'Northwoods Cranberry Sauce', UnitPrice: 40.0, Quantity: 10, Discontinued: true, ExtendedPrice: 340.0, Freight: 350.64 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 10755, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 47, ProductName: 'Zaanse koeken', UnitPrice: 9.5, Quantity: 30, Discontinued: true, ExtendedPrice: 213.75, Freight: 16.71 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 10755, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 56, ProductName: 'Gnocchi di nonna Alice', UnitPrice: 38.0, Quantity: 30, Discontinued: true, ExtendedPrice: 855.0, Freight: 16.71 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 10755, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 57, ProductName: 'Ravioli Angelo', UnitPrice: 19.5, Quantity: 14, Discontinued: true, ExtendedPrice: 204.75, Freight: 16.71 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 10755, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 69, ProductName: 'Gudbrandsdalsost', UnitPrice: 36.0, Quantity: 25, Discontinued: true, ExtendedPrice: 675.0, Freight: 16.71 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 11076, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 6, ProductName: "Grandma's Boysenberry Spread", UnitPrice: 25.0, Quantity: 20, Discontinued: true, ExtendedPrice: 375.0, Freight: 38.28 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 11076, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 14, ProductName: 'Tofu', UnitPrice: 23.25, Quantity: 20, Discontinued: true, ExtendedPrice: 348.75, Freight: 38.28 },
            { ShipName: "Bon app'", ShipAddress: '12, rue des Bouchers', ShipCity: 'Marseille', ShipRegion: null, ShipPostalCode: '13008', ShipCountry: 'France', CustomerID: 'BONAP', CustomerName: "Bon app'", Address: '12, rue des Bouchers', City: 'Marseille', Region: null, PostalCode: '13008', Country: 'France', Salesperson: 'Margaret Peacock', OrderID: 11076, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 19, ProductName: 'Teatime Chocolate Biscuits', UnitPrice: 9.2, Quantity: 10, Discontinued: true, ExtendedPrice: 69.0, Freight: 38.28 },
            { ShipName: 'Bottom-Dollar Markets', ShipAddress: '23 Toronto Blvd.', ShipCity: 'Toronto', ShipRegion: 'BC', ShipPostalCode: 'T2F 8M4', ShipCountry: 'Canada', CustomerID: 'BOTTM', CustomerName: 'Bottom-Dollar Markets', Address: '23 Toronto Blvd.', City: 'Toronto', Region: 'BC', PostalCode: 'T2F 8M4', Country: 'Canada', Salesperson: 'Margaret Peacock', OrderID: 10389, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 10, ProductName: 'Ikura', UnitPrice: 24.8, Quantity: 16, Discontinued: false, ExtendedPrice: 396.8, Freight: 47.42 },
            { ShipName: 'Bottom-Dollar Markets', ShipAddress: '23 Toronto Blvd.', ShipCity: 'Toronto', ShipRegion: 'BC', ShipPostalCode: 'T2F 8M4', ShipCountry: 'Canada', CustomerID: 'BOTTM', CustomerName: 'Bottom-Dollar Markets', Address: '23 Toronto Blvd.', City: 'Toronto', Region: 'BC', PostalCode: 'T2F 8M4', Country: 'Canada', Salesperson: 'Margaret Peacock', OrderID: 10389, OrderDate: new Date('10/4/2016'), ShipperName: 'United Package', ProductID: 55, ProductName: 'P\u00e2t\u00e9 chinois', UnitPrice: 19.2, Quantity: 15, Discontinued: false, ExtendedPrice: 288.0, Freight: 47.42 },
            { ShipName: 'Bottom-Dollar Markets', ShipAddress: '23 Tsawassen Blvd.', ShipCity: 'Tsawassen', ShipRegion: 'BC', ShipPostalCode: 'T2F 8M4', ShipCountry: 'Canada', CustomerID: 'BOTTM', CustomerName: 'Bottom-Dollar Markets', Address: '23 Tsawassen Blvd.', City: 'Tsawassen', Region: 'BC', PostalCode: 'T2F 8M4', Country: 'Canada', Salesperson: 'Margaret Peacock', OrderID: 10389, OrderDate: new Date('9/4/2018'), ShipperName: 'United Package', ProductID: 62, ProductName: 'Tarte au sucre', UnitPrice: 39.4, Quantity: 20, Discontinued: false, ExtendedPrice: 788.0, Freight: 47.42 }
        ];
    }

    public formatDate(val: Date) {
        return new Intl.DateTimeFormat('en-US').format(val);
    }

    public formatCurrency(value: number) {
        return '$' + value.toFixed(2);
    }

    public isDate(value: any) {
        if (value instanceof Date) {
            return true;
        } else {
            return false;
        }
    }

    public calc2017(values: any[]) {
        const startDate = new Date('1/1/2017');
        const endDate = new Date('12/31/2017');
        return values.filter((x) => x.OrderDate >= startDate && x.OrderDate <= endDate).length;
    }
}
